{
 "title": "MinIO Overview",
 "description": "Overview of single MinIO cluster",
 "tags": [
  "Pigsty",
  "MINIO",
  "HOME",
  "OVERVIEW"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cls",
    "label": "Cluster",
    "query": {
     "query": "label_values(minio_node_process_uptime_seconds,cls)"
    }
   },
   {
    "name": "members",
    "label": "Members",
    "query": {
     "query": "label_values(minio_up{cls=\"$cls\"},ip)"
    }
   },
   {
    "name": "ins",
    "label": "Instance",
    "query": {
     "query": "label_values(minio_node_process_uptime_seconds{cls='$cls'}, ins)"
    }
   },
   {
    "name": "ip",
    "label": "IP",
    "query": {
     "query": "label_values(minio_node_process_uptime_seconds{ins=\"$ins\"}, ip)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "MinIO Members",
   "type": "table",
   "description": "MinIO cluster members",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "group by (cls,server,version) (minio_software_version_info{job=\"minio\", cls=\"$cls\"})"
    },
    {
     "expr": "max by (server,ins,instance,ip) (minio_cluster_capacity_usable_total_bytes{job=\"minio\", cls=\"$cls\"})"
    },
    {
     "expr": "max by (server) (minio_cluster_capacity_usable_free_bytes{job=\"minio\", cls=\"$cls\"})"
    },
    {
     "expr": "max by (server) (minio_cluster_capacity_usable_total_bytes{job=\"minio\", cls=\"$cls\"})\n- max by (server) (minio_cluster_capacity_usable_free_bytes{job=\"minio\", cls=\"$cls\"})"
    },
    {
     "expr": "1 - \nmax by (server) (minio_cluster_capacity_usable_free_bytes{job=\"minio\", cls=\"$cls\"}) /\nmax by (server) (minio_cluster_capacity_usable_total_bytes{job=\"minio\", cls=\"$cls\"})\n "
    },
    {}
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "max(minio_cluster_nodes_online_total{ins=\"$ins\"})",
     "legendFormat": "Nodes Online"
    },
    {
     "expr": "max(minio_cluster_nodes_offline_total{ins=\"$ins\"})",
     "legendFormat": "Nodes Offline"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "max(minio_cluster_drive_online_total{ins=\"$ins\"})",
     "legendFormat": "Driver Online"
    },
    {
     "expr": "max(minio_cluster_drive_offline_total{ins=\"$ins\"})",
     "legendFormat": "Driver Offline"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(minio_cluster_bucket_total{ins=\"$ins\"})",
     "legendFormat": "Buckets"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(minio_cluster_usage_object_total{ins=\"$ins\"})",
     "legendFormat": "Objects"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(minio_cluster_usage_total_bytes{ins=\"$ins\"})",
     "legendFormat": "Data Size"
    },
    {
     "expr": "max(minio_cluster_capacity_usable_total_bytes{ins=\"$ins\"} - minio_cluster_capacity_usable_free_bytes{ins=\"$ins\"})",
     "legendFormat": "Used Size"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(minio_cluster_capacity_raw_total_bytes{ins=\"$ins\"})",
     "legendFormat": "Raw Disk"
    },
    {
     "expr": "max(minio_cluster_capacity_usable_total_bytes{ins=\"$ins\"})",
     "legendFormat": "Usable Disk"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1 - (minio_cluster_capacity_usable_free_bytes{ins=\"$ins\"} / minio_cluster_capacity_usable_total_bytes{ins=\"$ins\"})",
     "legendFormat": "Usage%"
    },
    {
     "expr": "max(minio_cluster_capacity_usable_total_bytes{ins=\"$ins\"} - minio_cluster_capacity_usable_free_bytes{ins=\"$ins\"}) /\nmax(minio_cluster_usage_total_bytes{ins=\"$ins\"})",
     "legendFormat": "Space / Data"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(minio_s3_requests_total{ins=\"$ins\"}[1m]))",
     "legendFormat": "QPS"
    },
    {
     "expr": "sum(rate(minio_s3_requests_errors_total{ins=\"$ins\"}[1m]))",
     "legendFormat": "Errors"
    }
   ]
  },
  { "title": "QPS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "QPS by API (rate1m)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (api) (rate(minio_s3_requests_total{ins=\"$ins\"}[1m]))",
     "legendFormat": "{{ api }}"
    }
   ]
  },
  {
   "title": "Error by API (rate1m)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (api) (rate(minio_s3_requests_errors_total{ins=\"$ins\"}[1m]))",
     "legendFormat": "{{ api }}"
    }
   ]
  },
  {
   "title": "QPS by Server (rate1m)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (server) (rate(minio_s3_requests_total{ins=\"$ins\"}[1m]))",
     "legendFormat": "{{ api }}"
    }
   ]
  },
  {
   "title": "Error by Server (rate1m)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (server) (rate(minio_s3_requests_errors_total{ins=\"$ins\"}[1m]))",
     "legendFormat": "{{ api }}"
    }
   ]
  },
  { "title": "Bucket", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "Object Count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "minio_cluster_usage_object_total{cls=\"$cls\"}",
     "legendFormat": "{{ server }}"
    }
   ]
  },
  {
   "title": "Object Size Distribution",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 30 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum by (range) (minio_cluster_objects_size_distribution{cls=\"$cls\"})",
     "legendFormat": "{{range}}"
    }
   ]
  },
  {
   "title": "Receive Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "rate(minio_s3_traffic_received_bytes{ins=\"$ins\"}[1m])",
     "legendFormat": "{{ server }}"
    }
   ]
  },
  {
   "title": "Sent / Transmit Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(minio_s3_traffic_sent_bytes{ins=\"$ins\"}[1m])",
     "legendFormat": "{{ server }}"
    }
   ]
  },
  { "title": "Resource", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } },
  {
   "title": "Node CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(minio_node_process_cpu_total_seconds{ins=\"$ins\"}[1m])",
     "legendFormat": "{{ server }}"
    }
   ]
  },
  {
   "title": "Node Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "minio_node_process_resident_memory_bytes{ins=\"$ins\"}",
     "legendFormat": "{{ server }}"
    }
   ]
  },
  {
   "title": "Node Syscalls",
   "type": "timeseries",
   "description": "Number of online disks per MinIO Server",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(minio_node_syscall_read_total{ins=\"$ins\"}[1m])",
     "legendFormat": "▲{{server}}"
    },
    {
     "expr": "- rate(minio_node_syscall_write_total{ins=\"$ins\"}[1m])",
     "legendFormat": "▼{{server}}"
    }
   ]
  },
  {
   "title": "Node I/O Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(minio_node_io_read_bytes{ins=\"$ins\"}[5m])",
     "legendFormat": "▲{{server}}"
    },
    {
     "expr": "- rate(minio_node_io_write_bytes{ins=\"$ins\"}[5m])",
     "legendFormat": "▼{{server}}"
    }
   ]
  },
  {
   "title": "MinIO Erasure Set",
   "type": "table",
   "description": "MinIO cluster members",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 63 },
   "targets": [
    {
     "expr": "minio_cluster_health_erasure_set_status{job=\"minio\", cls=\"$cls\"}"
    },
    {
     "expr": "minio_cluster_health_erasure_set_online_drives{job=\"minio\", cls=\"$cls\"}"
    },
    {
     "expr": "minio_cluster_health_erasure_set_healing_drives{job=\"minio\", cls=\"$cls\"}"
    },
    {
     "expr": "minio_cluster_health_erasure_set_read_quorum{job=\"minio\", cls=\"$cls\"}"
    },
    {
     "expr": "minio_cluster_health_erasure_set_write_quorum{job=\"minio\", cls=\"$cls\"}"
    }
   ]
  },
  { "title": "Disk", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 70 } },
  {
   "title": "Read/Write IOPS",
   "type": "timeseries",
   "description": "▲ for read IOPS, ▼ for write IOPS ",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node:ins:disk_reads_rate1m{cls=\"$cls\"}",
     "legendFormat": "▲{{ ins }}"
    },
    {
     "expr": "- node:ins:disk_writes_rate1m{cls=\"$cls\"}",
     "legendFormat": "▼{{ ins }}"
    }
   ]
  },
  {
   "title": "Read/Write Bandwidth",
   "type": "timeseries",
   "description": "▲ for read bandwidth, ▼ for write bandwidth",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "node:ins:disk_read_bytes_rate1m{cls=\"$cls\"}",
     "legendFormat": "▲{{ ins }}"
    },
    {
     "expr": "- node:ins:disk_write_bytes_rate1m{cls=\"$cls\"}",
     "legendFormat": "▼{{ ins }}"
    }
   ]
  },
  {
   "title": "Instant Queue Size",
   "type": "timeseries",
   "description": "Number of items which were in the queue at the sampling time point",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "node_disk_io_now{cls=\"$cls\"}",
     "legendFormat": "{{ ins }}:{{ device }}"
    }
   ]
  },
  {
   "title": "Read/Write Await Time",
   "type": "timeseries",
   "description": "▲ for read rt, ▼ for write rt",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "node:dev:disk_read_rt_1m{cls=\"$cls\"}",
     "legendFormat": "▲{{ ins }}:{{ device }}"
    },
    {
     "expr": "- node:dev:disk_write_rt_1m{cls=\"$cls\"}",
     "legendFormat": "▼{{ ins }}:{{ device }}"
    }
   ]
  },
  {
   "title": "Storage Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 87 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1 - (minio_cluster_capacity_usable_free_bytes{ins=\"$ins\"} / minio_cluster_capacity_usable_total_bytes{ins=\"$ins\"})",
     "legendFormat": "Usage"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 87 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "node:fs:space_usage{cls=\"$cls\"}",
     "legendFormat": "{{ ins }}:{{ mountpoint }}"
    }
   ]
  },
  { "title": "Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 95 } },
  {
   "title": "MinIO Logs per $__interval",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 96 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (ins,src) (count_over_time(({ip=~\"$members\", src=\"syslog\"} |~ \"minio\")[$__interval]))",
     "legendFormat": "{{ ins }}"
    }
   ]
  },
  {
   "title": "MinIO Logs",
   "type": "logs",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 102 },
   "targets": [
    {
     "expr": "{ip=~\"$members\", src=\"syslog\"} |~ \"minio\""
    }
   ]
  }
 ]
}