{
 "title": "MinIO Instance",
 "description": "MinIO Instance",
 "tags": [
  "Pigsty",
  "MINIO",
  "INSTANCE"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "ins",
    "label": "Instance",
    "query": {
     "query": "label_values(minio_node_process_uptime_seconds, ins)"
    }
   },
   {
    "name": "cls",
    "label": "Cluster",
    "query": {
     "query": "label_values(minio_node_process_uptime_seconds{ins=\"$ins\"}, cls)"
    }
   },
   {
    "name": "ip",
    "label": "IP",
    "query": {
     "query": "label_values(minio_node_process_uptime_seconds{ins=\"$ins\"}, ip)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_uname_info{ip=\"$ip\"}",
     "legendFormat": "Instance"
    },
    {
     "expr": "min by (job,ip,vip) (probe_success{ip=\"$ip\", job=~'(node|pgsql)-vip'})",
     "legendFormat": "{{ job }} : {{ vip }}"
    }
   ]
  },
  {
   "title": "MinIO Members",
   "type": "table",
   "description": "MinIO cluster members",
   "gridPos": { "h": 6, "w": 18, "x": 6, "y": 1 },
   "targets": [
    {
     "expr": "group by (cls,server,version) (minio_software_version_info{job=\"minio\", cls=\"$cls\"})"
    },
    {
     "expr": "max by (server,ins,instance,ip) (minio_cluster_capacity_usable_total_bytes{job=\"minio\", cls=\"$cls\"})"
    },
    {
     "expr": "max by (server) (minio_cluster_capacity_usable_free_bytes{job=\"minio\", cls=\"$cls\"})"
    },
    {
     "expr": "max by (server) (minio_cluster_capacity_usable_total_bytes{job=\"minio\", cls=\"$cls\"})\n- max by (server) (minio_cluster_capacity_usable_free_bytes{job=\"minio\", cls=\"$cls\"})"
    },
    {
     "expr": "1 - \nmax by (server) (minio_cluster_capacity_usable_free_bytes{job=\"minio\", cls=\"$cls\"}) /\nmax by (server) (minio_cluster_capacity_usable_total_bytes{job=\"minio\", cls=\"$cls\"})\n "
    },
    {}
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "minio_cluster_nodes_online_total{ins=\"$ins\"}",
     "legendFormat": "Nodes Online"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "minio_cluster_drive_online_total{ins=\"$ins\"}",
     "legendFormat": "Disks Online"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(minio_s3_requests_total{cls=\"$cls\"}[1m]))",
     "legendFormat": "QPS"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1 - (minio_cluster_capacity_usable_free_bytes{ins=\"$ins\"} / minio_cluster_capacity_usable_total_bytes{ins=\"$ins\"})",
     "legendFormat": "Usage%"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "minio_cluster_capacity_usable_total_bytes{ins=\"$ins\"}",
     "legendFormat": "Size"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "minio_cluster_capacity_usable_total_bytes{ins=\"$ins\"} - \nminio_cluster_capacity_usable_free_bytes{ins=\"$ins\"}",
     "legendFormat": "Used"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(minio_cluster_bucket_total{ins=\"$ins\"})",
     "legendFormat": "Buckets"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(minio_cluster_usage_object_total{ins=\"$ins\"})",
     "legendFormat": "Objects"
    }
   ]
  },
  { "title": "QPS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "S3 API QPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (server,api) (increase(minio_s3_requests_total{ins=\"$ins\", server=~'.*$ins.*'}[$__rate_interval]))",
     "legendFormat": "{{ api }}"
    }
   ]
  },
  {
   "title": "S3 ERROR QPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (server,api) (increase(minio_s3_requests_errors_total{ins=\"$ins\", server=~'.*$ins.*'}[$__rate_interval]))",
     "legendFormat": "{{ api }}"
    }
   ]
  },
  { "title": "Bucket", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Object Count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(bucket) (minio_cluster_usage_object_total{ins=\"$ins\"})",
     "legendFormat": "{{ ins }}"
    }
   ]
  },
  {
   "title": "Object Size Distribution",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "max by (range) (minio_cluster_objects_size_distribution{ins=\"$ins\", server=~'.*$ins.*'})",
     "legendFormat": "{{range}}"
    }
   ]
  },
  {
   "title": "Transmit by Bucket",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "minio_s3_traffic_sent_bytes{ins=\"$ins\", server=~'.*$ins.*'}",
     "legendFormat": "{{ ins }}"
    }
   ]
  },
  {
   "title": "Receive by Bucket",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "minio_s3_traffic_sent_bytes{ins=\"$ins\"}",
     "legendFormat": "{{ server }}"
    }
   ]
  },
  { "title": "Resource", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "Node CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(minio_node_process_cpu_total_seconds{ins=\"$ins\", server=~'.*$ins.*'}[1m])",
     "legendFormat": "{{ server }}"
    }
   ]
  },
  {
   "title": "Node Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "minio_node_process_resident_memory_bytes{ins=\"$ins\", server=~'.*$ins.*'}",
     "legendFormat": "{{ server }}"
    }
   ]
  },
  {
   "title": "Node Syscalls",
   "type": "timeseries",
   "description": "Number of online disks per MinIO Server",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(minio_node_syscall_read_total{ins=\"$ins\", server=~'.*$ins.*'}[$__rate_interval])",
     "legendFormat": "Read Syscalls [{{server}}]"
    },
    {
     "expr": "rate(minio_node_syscall_write_total{ins=\"$ins\", server=~'.*$ins.*'}[1m])",
     "legendFormat": "Write Syscalls [{{server}}]"
    }
   ]
  },
  {
   "title": "Node IO (rate1m)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(minio_node_io_rchar_bytes{ins=\"$ins\", server=~'.*$ins.*'}[1m])",
     "legendFormat": "Node RChar"
    },
    {
     "expr": "- rate(minio_node_io_wchar_bytes{ins=\"$ins\", server=~'.*$ins.*'}[1m])",
     "legendFormat": "Node WChar"
    }
   ]
  }
 ]
}