---
#--------------------------------------------------------------#
# NODE EXPORTER
#--------------------------------------------------------------#
node_exporter_enabled: true       # setup node_exporter on this node?
node_exporter_port: 9100          # node exporter listen port, 9100 by default
node_exporter_options: '--no-collector.softnet --no-collector.nvme --collector.tcpstat --collector.processes'
#--------------------------------------------------------------#
# PROMTAIL (Deprecated)
#--------------------------------------------------------------#
promtail_enabled: true            # enable promtail logging collector? (deprecated)
promtail_clean: false             # purge the existing promtail status file during init?
promtail_port: 9080               # promtail listen port, 9080 by default
promtail_positions: /var/log/positions.yaml # promtail position status file path
#--------------------------------------------------------------#
# VECTOR (Log Collection Agent)
#--------------------------------------------------------------#
vector_enabled: true                    # enable vector on this node?
vector_port: 8686                       # vector API port
vector_config_dir: /etc/vector          # vector configuration directory
vector_data_dir: /var/lib/vector        # vector data directory
vector_log_level: info                  # log level: error, warn, info, debug, trace

# System log paths
vector_syslog_paths:
  - "/var/log/syslog"                    # Ubuntu/Debian
  - "/var/log/messages"                  # RHEL/CentOS

# Docker log collection (auto-detected via socket)
vector_docker_socket: "unix:///var/run/docker.sock"

# PostgreSQL log collection (auto-detected for database nodes)
vector_postgres_log_dir: "{{ pg_log_dir | dirname }}"  # postgresql log directory (reuses pg_log_dir)
vector_postgres_log_pattern: "postgres/*.json"  # PostgreSQL JSON logs

# Nginx log collection (auto-detected for infra nodes)
vector_nginx_access_logs: "/var/log/nginx/access.log"
vector_nginx_error_logs: "/var/log/nginx/error.log"

# Redis log collection (auto-detected for redis nodes)
vector_redis_log_dir: "/var/log/redis"
vector_redis_log_pattern: "*.log"

# VECTOR PERFORMANCE SETTINGS  
vector_buffer_max_events: 10000         # max events in memory buffer
vector_buffer_when_full: "block"        # what to do when buffer full: block, drop_newest
vector_batch_max_events: 1000           # max events per batch
vector_batch_timeout_ms: 5000           # batch timeout in milliseconds
vector_compression: "gzip"              # compression: none, gzip, lz4, snappy
vector_healthcheck_enabled: false       # enable health checks (can cause issues)

# STREAM FIELDS (for VictoriaLogs)
# Fields used for log stream identification in VictoriaLogs
vector_stream_fields: "host,job,src"    # comma-separated stream fields
vector_msg_field: "message"             # field containing log message
vector_time_field: "timestamp"          # field containing timestamp
#-----------------------------------------------------------------
# NODE_VIP (Reference)
#-----------------------------------------------------------------
vip_enabled: false                # enable vip on this node cluster?
# vip_address:         [IDENTITY] # node vip address in ipv4 format, required if vip is enabled
vip_dns_suffix: ''                # node vip dns name suffix, empty string by default
vip_exporter_port: 9650           # keepalived exporter listen port, 9650 by default
#-----------------------------------------------------------------
# PROMETHEUS (Reference)
#-----------------------------------------------------------------
prometheus_sd_dir: /etc/prometheus/targets # prometheus file service discovery directory
#-----------------------------------------------------------------
# EXPORTER (Reference)
#-----------------------------------------------------------------
exporter_install: none            # how to install exporter? none|yum|binary
exporter_repo_url: ''             # exporter repo file url if install exporter via yum
exporter_metrics_path: /metrics   # exporter metric path
#-----------------------------------------------------------------
# HAPROXY (Reference)
#-----------------------------------------------------------------
haproxy_enabled: true             # enable haproxy on this node?
haproxy_exporter_port: 9101       # haproxy admin/exporter port, 9101 by default
#-----------------------------------------------------------------
# PGSQL (Reference)
#-----------------------------------------------------------------
patroni_enabled: true             # if disabled, no postgres cluster will be created during init
pgbouncer_enabled: true           # if disabled, pgbouncer will not be launched on pgsql host
pgbackrest_enabled: true          # enable pgbackrest on pgsql host?
pg_log_dir: /pg/log/postgres      # postgres log dir, `/pg/log/postgres` by default
patroni_log_dir: /pg/log/patroni  # patroni log dir, `/pg/log/patroni` by default
pgbouncer_log_dir: /pg/log/pgbouncer  # pgbouncer log dir, `/pg/log/pgbouncer` by default
pgbackrest_log_dir: /pg/log/pgbackrest # pgbackrest log dir, `/pg/log/pgbackrest` by default
#-----------------------------------------------------------------
# INFRA (Reference)
#-----------------------------------------------------------------
infra_portal: {loki : {endpoint: "${admin_ip}:3100"}}
victoria_logs_port: 3100          # VictoriaLogs port for Vector sink endpoints
...