{
 "title": "HA Cron",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Executed [72h]",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(ha_cron_job_executed_total[72h]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Successful [72h]",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(ha_cron_job_success_total[72h]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Failed [72h]",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(ha_cron_job_failed_total[72h]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Last Job",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(time() - max (ha_cron_job_last_run_timestamp)) / 60",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Last Status Cache Refresh",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(time() - max (ha_cron_job_last_run_timestamp{job_name=\"refresh-status-cache\"})) / 60",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Last Hourly Maintenance",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(time() - max (ha_cron_job_last_run_timestamp{job_name=\"hourly-maintenance\"})) / 60",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Job Duration",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by(job_name) (ha_cron_job_duration_seconds)",
     "legendFormat": "{{ip}} {{job_name}}"
    }
   ]
  },
  {
   "title": "Success/Failure",
   "type": "state-timeline",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "min by(job_name) (ha_cron_job_success)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Successful Runs",
   "type": "state-timeline",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "(sum by (job_name) (increase(ha_cron_job_success_total[5m])) == 1)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Success Rates", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "72h Success Rate by Job",
   "type": "gauge",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (job_name) (increase(ha_cron_job_success_total[72h])) / sum by (job_name) (increase(ha_cron_job_executed_total[72h])) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Lock Holders", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 } },
  {
   "title": "cron0",
   "type": "state-timeline",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 54 },
   "targets": [
    {
     "expr": "ha_cron_lock_acquired{ins=~\".+-fmpcron-0\"}",
     "legendFormat": "{{job_name}}"
    }
   ]
  },
  {
   "title": "cron1",
   "type": "state-timeline",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 61 },
   "targets": [
    {
     "expr": "ha_cron_lock_acquired{ins=~\".+-fmpcron-1\"}",
     "legendFormat": "{{job_name}}"
    }
   ]
  },
  {
   "title": "cron2",
   "type": "state-timeline",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 68 },
   "targets": [
    {
     "expr": "ha_cron_lock_acquired{ins=~\".+-fmpcron-2\"}",
     "legendFormat": "{{job_name}}"
    }
   ]
  }
 ]
}