{
 "title": "MPW Nodes",
 "tags": [
  "mpw",
  "nodes"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "cls",
    "label": "Cluster",
    "query": {
     "query": "label_values(up{job=\"node\"}, cls)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Nodes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(up{job=\"node\",cls=~\"$cls\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Down",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(up{job=\"node\",cls=~\"$cls\"}) - sum(up{job=\"node\",cls=~\"$cls\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Need reboot",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_reboot_required{cls=~\"$cls\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Kernel stale",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_kernel_stale{cls=~\"$cls\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Nodes",
   "type": "table",
   "gridPos": { "h": 20, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "max by (ins, cls, ip) (up{job=\"node\",cls=~\"$cls\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by (ins, pkgs) (node_reboot_required{cls=~\"$cls\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by (ins, running, installed) (node_kernel_stale{cls=~\"$cls\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by (ins) (time() - node_boot_time_seconds{cls=~\"$cls\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "100 - avg by (ins) (rate(node_cpu_seconds_total{mode=\"idle\",cls=~\"$cls\"}[5m])) * 100",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by (ins) (100 * (1 - node_memory_MemAvailable_bytes{cls=~\"$cls\"} / node_memory_MemTotal_bytes{cls=~\"$cls\"}))",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by (ins) (100 - node_filesystem_avail_bytes{mountpoint=\"/\",fstype!~\"tmpfs|overlay\",cls=~\"$cls\"} / node_filesystem_size_bytes{mountpoint=\"/\",fstype!~\"tmpfs|overlay\",cls=~\"$cls\"} * 100)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}