{
 "title": "Node VIP",
 "description": "VIP Metrics (Keepalived & VIP-Manager)",
 "tags": [
  "Pigsty",
  "NODE",
  "INSTANCE",
  "VIP"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "vip",
    "label": "VIP",
    "query": {
     "query": "label_values(probe_success,vip)"
    }
   },
   {
    "name": "ip",
    "label": "IP",
    "query": {
     "query": "label_values(probe_success{vip=\"$vip\"},ip)"
    }
   },
   {
    "name": "cls",
    "label": "Node Cluster",
    "query": {
     "query": "label_values(probe_success{vip=\"$vip\"},cls)"
    }
   },
   {
    "name": "pg_cls",
    "label": "PG Cluster",
    "query": {
     "query": "label_values(pg_up{ip=~\"$ip\"},cls)"
    }
   },
   {
    "name": "type",
    "label": "Type",
    "query": {
     "query": "label_values(probe_success{vip=\"$vip\"},job)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min by (job,cls,vip) (probe_success{vip=\"$vip\"})"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (job,vip) (probe_duration_seconds{cls=\"$cls\", job=~\".*vip\"})",
     "legendFormat": "{{ vip }} @ {{ job }}"
    },
    {
     "expr": "probe_duration_seconds{cls=\"$cls\", job=\"ping\"}",
     "legendFormat": "{{ ip }} : {{ ins }}"
    }
   ]
  },
  {
   "title": "Ping Status",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "probe_success{ip=~\"$ip\", job=\"ping\"}"
    },
    {
     "expr": "max by (ip) (probe_duration_seconds{ip=~\"$ip\", job=\"ping\"})"
    },
    {
     "expr": "max by (ip) (probe_dns_lookup_time_seconds{ip=~\"$ip\", job=\"ping\"})"
    },
    {
     "expr": "max by (ip) (probe_icmp_duration_seconds{ip=~\"$ip\", job=\"ping\", phase=\"setup\"})"
    },
    {
     "expr": "max by (ip) (probe_icmp_duration_seconds{ip=~\"$ip\", job=\"ping\", phase=\"rtt\"})"
    },
    {
     "expr": "max by (ip) (probe_icmp_duration_seconds{ip=~\"$ip\", job=\"ping\", phase=\"resolve\"})"
    }
   ]
  },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "keepalived_vrrp_state{vip=\"$vip\"} - 1",
     "legendFormat": "{{ ip }} : {{ ins }}"
    }
   ]
  },
  {
   "title": "Keepalived Status",
   "type": "table",
   "gridPos": { "h": 6, "w": 18, "x": 6, "y": 7 },
   "targets": [
    {
     "expr": "keepalived_exporter_up{vip=\"$vip\"} * on(ins) group_left()\nkeepalived_up{vip=\"$vip\"} or on (ins) keepalived_exporter_up{vip=\"$vip\"}"
    },
    {
     "expr": "max by (ins,state,vrid,name) (keepalived_become_master_total{vip=\"$vip\"})"
    },
    {
     "expr": "max by (ins) (keepalived_release_master_total{vip=\"$vip\"})"
    },
    {
     "expr": "max by (ins) (rate(keepalived_advertisements_received_total{vip=\"$vip\"}[1m]))"
    },
    {
     "expr": "max by (ins) (rate(keepalived_advertisements_sent_total{vip=\"$vip\"}[1m]))"
    },
    {
     "expr": "max by (ins) (keepalived_priority_zero_received_total{vip=\"$vip\"})"
    },
    {
     "expr": "max by (ins) (keepalived_priority_zero_sent_total{vip=\"$vip\"})"
    },
    {
     "expr": "max by (ins) (keepalived_ip_ttl_errors_total{vip=\"$vip\"})"
    },
    {
     "expr": "max by (ins) (keepalived_invalid_type_received_total{vip=\"$vip\"})"
    },
    {
     "expr": "max by (ins) (keepalived_address_list_errors_total{vip=\"$vip\"})"
    },
    {
     "expr": "max by (ins) (keepalived_authentication_invalid_total{vip=\"$vip\"})"
    },
    {
     "expr": "max by (ins) (keepalived_authentication_mismatch_total{vip=\"$vip\"})"
    },
    {
     "expr": "max by (ins) (keepalived_authentication_failure_total{vip=\"$vip\"})"
    },
    {
     "expr": "max by (ins) (keepalived_packet_length_errors_total{vip=\"$vip\"})"
    },
    {
     "expr": "max by (ins) (keepalived_advertisements_interval_errors_total{vip=\"$vip\"})"
    },
    {
     "expr": "max by (ins) (keepalived_vrrp_state{vip=\"$vip\"})"
    }
   ]
  },
  {
   "title": "Status Timeline",
   "type": "state-timeline",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "keepalived_vrrp_state{vip=\"$vip\"} - 1",
     "legendFormat": "{{ ip }} : {{ ins }}"
    }
   ]
  },
  {
   "title": "Advertisements Sent/Recv iRate1m",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (ins) (irate(keepalived_advertisements_sent_total{vip=\"$vip\"}[1m]))",
     "legendFormat": "{{ ins }} Sent"
    },
    {
     "expr": "sum by (ins) (irate(keepalived_advertisements_received_total{vip=\"$vip\"}[1m]))",
     "legendFormat": "{{ ins }} Recv"
    }
   ]
  },
  {
   "title": "Nodes",
   "type": "table",
   "description": "Node list of ${ip}",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "node_up{ip=~\"$ip\"}"
    },
    {
     "expr": "group without(ins,cls,instance) (node_uname_info{ip=~\"$ip\"})"
    },
    {
     "expr": "max by (ip) (node:ins:cpu_usage{ip=~\"$ip\"})"
    },
    {
     "expr": "max by (ip) (node:ins:mem_usage{ip=~\"$ip\"})"
    },
    {
     "expr": "sum by (ip,instance) (node:ins:space_usage_max{ip=~\"$ip\"})"
    },
    {
     "expr": "max by (ip) (node:ins:cpu_count{ip=~\"$ip\"}) "
    },
    {
     "expr": "max by (ip) (node_memory_MemTotal_bytes{ip=~\"$ip\"}) / 1073741824"
    },
    {
     "expr": "sum(node:fs:size_bytes{ip=~\"$ip\"}) by (ip) / 1073741824"
    },
    {
     "expr": "count by (ip) (up{ip=~\"$ip\"})"
    },
    {
     "expr": "max by (ip) (probe_duration_seconds{ip=~\"$ip\", job=\"ping\"})"
    },
    {
     "expr": "sum by (ip) (haproxy_backend_current_sessions{ip=~\"$ip\"})"
    },
    {
     "expr": "min by (ip) (node_up{ip=~\"$ip\"})"
    }
   ]
  },
  { "title": "Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Keepalived Service Status",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 26 },
   "repeat": "instance",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "keepalived_up{vip=\"$vip\"}",
     "legendFormat": "{{ ins }}"
    }
   ]
  },
  {
   "title": "Keepalived Advertisement interval errors",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (ins) (irate(keepalived_advertisements_interval_errors_total{vip=\"$vip\"}[1m]))",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "TTL errors",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (ins) (irate(keepalived_ip_ttl_errors_total{vip=\"$vip\"}[1m]))",
     "legendFormat": "{{ ins }}"
    }
   ]
  },
  {
   "title": "Authentication invalid",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (ins) (irate(keepalived_authentication_invalid_total{vip=\"$vip\"}[1m]))",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Authentication mismatch",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (ins) (irate(keepalived_authentication_mismatch_total{vip=\"$vip\"}[1m]))",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Authentication failure",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (ins) (irate(keepalived_authentication_mismatch_total{vip=\"$vip\"}[1m]))",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Keepalived Address list errors",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (ins) (irate(keepalived_address_list_errors_total{vip=\"$vip\"}[1m]))",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Packet length errors",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (ins) (irate(keepalived_packet_length_errors_total{vip=\"$vip\"}[1m]))",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Invalid type errors",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (ins) (irate(keepalived_invalid_type_received_total{vip=\"$vip\"}[1m]))",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Priority zero sent",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (ins) (irate(keepalived_priority_zero_sent_total{vip=\"$vip\"}[1m]))",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Priority zero received",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (ins) (irate(keepalived_priority_zero_received_total{vip=\"$vip\"}[1m]))",
     "legendFormat": "{{state}}"
    }
   ]
  }
 ]
}