{
 "title": "PGLOG Overview",
 "description": "PostgreSQL CSVLog Sample Analysis",
 "tags": [
  "APP",
  "PGLOG",
  "Overview"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "log", "label": "Log Table", "query": "pglog.sample" },
   {
    "name": "ts_begin",
    "label": "TimeBegin",
    "query": "SELECT min(ts) - '5min'::INTERVAL FROM ${log};"
   },
   {
    "name": "ts_end",
    "label": "Time End",
    "query": "SELECT max(ts) + '5min'::INTERVAL FROM ${log};"
   }
  ]
 },
 "panels": [
  {
   "title": "Log Events",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT $__timeGroup(ts, $__interval) AS \"time\", count(*) AS value \nFROM ${log} WHERE $__timeFilter(ts)\nGROUP BY 1 ORDER BY 1;"
    }
   ]
  },
  {
   "title": "Log Events by Level",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT $__timeGroup(ts, $__interval) AS \"time\", \n       level AS metric, count(*) AS value \nFROM ${log}\nWHERE $__timeFilter(ts)\nGROUP BY 1, 2\nORDER BY 1, 2;"
    }
   ]
  },
  {
   "title": "Log Event by ErrCode",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT $__timeGroup(ts, $__interval) AS \"time\", \n       code AS metric, count(*) AS value \nFROM ${log}\nWHERE $__timeFilter(ts)\nGROUP BY 1, 2\nORDER BY 1, 2;"
    }
   ]
  },
  {
   "title": "Count by CmdTag",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT $__timeGroup(ts, $__interval) AS \"time\", \n       cmd_tag AS metric, count(*) AS value \nFROM ${log}\nWHERE $__timeFilter(ts)\nGROUP BY 1, 2\nORDER BY 1, 2;"
    }
   ]
  },
  {
   "title": "Log Events by Database",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT $__timeGroup(ts, $__interval) AS \"time\", \n       CASE WHEN datname IS NULL OR datname = '' THEN '<system>' ELSE datname END AS metric, count(*) AS value \nFROM ${log}\nWHERE $__timeFilter(ts)\nGROUP BY 1, 2\nORDER BY 1, 2;"
    }
   ]
  },
  {
   "title": "Log Events by Username",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT $__timeGroup(ts, $__interval) AS \"time\", \n       coalesce(username, '<null>') AS metric, count(*) AS value \nFROM ${log}\nWHERE $__timeFilter(ts)\nGROUP BY 1, 2\nORDER BY 1, 2;"
    }
   ]
  },
  {
   "title": "Connection",
   "type": "table",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT conn, count(*)\nFROM ${log}\nWHERE $__timeFilter(ts)\nGROUP BY conn ORDER BY 1;"
    }
   ]
  },
  {
   "title": "Application",
   "type": "table",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT appname AS app, count(*) AS count \nFROM ${log}\nWHERE $__timeFilter(ts) GROUP BY 1 ORDER BY 1;"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "rawSql": "SELECT * FROM ${log} WHERE $__timeFilter(ts) ORDER BY ts DESC LIMIT 1000;"
    }
   ]
  },
  {
   "title": "How to use PGLOG Analysis ?",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 34 },
     "options": {
      "content": "Run on meta node as admin user to fetch and pour log into sample table: `$log`\n```\ncatlog | pglog                       # get local (metadb) today's log\ncatlog node-1 | pglog                # get certain node today's log\ncatlog node-1 '2022-03-20' | pglog   # get node-1's csvlog @ 2022-03-20\n# pg12, 13, 14 have different csvlog schema, use pglog12, pglog13 instead\n```"
     }
    }
   ]
  }
 ]
}