{
 "title": "PGCAT Query",
 "description": "PostgreSQL Catalog Explorer for Query",
 "tags": [
  "Pigsty",
  "PGSQL",
  "PGCAT",
  "Database",
  "Query"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "dsn", "label": "Data Source", "query": "postgres" },
   { "name": "ins", "label": "Instance", "query": "SELECT '${dsn:text}';" },
   { "name": "datname", "label": "Database", "query": "SELECT '${dsn:text}';" },
   {
    "name": "query",
    "label": "Query",
    "query": "SELECT distinct queryid::TEXT FROM pg_stat_statements WHERE dbid = (SELECT oid FROM pg_database WHERE datname = '${datname}') AND userid != 10 LIMIT 1000;"
   },
   { "name": "cls", "label": "Cluster", "query": "SELECT '${dsn:text}';" }
  ]
 },
 "panels": [
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "frame": {
      "fields": [
       {
        "config": {},
        "name": "Query",
        "type": "string",
        "values": [ "${query}" ]
       }
      ],
      "meta": {},
      "name": ""
     }
    },
    {
     "frame": {
      "fields": [
       {
        "config": {},
        "name": "Database",
        "type": "string",
        "values": [ "${datname}" ]
       }
      ],
      "meta": {},
      "name": ""
     }
    },
    {
     "frame": {
      "fields": [
       {
        "config": {},
        "name": "Instance",
        "type": "string",
        "values": [ "$ins" ]
       }
      ],
      "meta": {},
      "name": ""
     }
    },
    {
     "frame": {
      "fields": [
       {
        "config": {},
        "name": "Cluster",
        "type": "string",
        "values": [ "${cls}" ]
       }
      ],
      "meta": {},
      "name": ""
     }
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 5, "w": 18, "x": 6, "y": 0 },
   "targets": [
    {
     "legendFormat": "__auto",
     "rawSql": "SELECT queryid::TEXT AS qid, d.datname, r.rolname, s.*\nFROM pg_stat_statements s\n         LEFT JOIN pg_database d ON s.dbid = d.oid\n         LEFT JOIN pg_roles r ON s.userid = r.oid\nWHERE datname='$datname'\nORDER BY mean_exec_time DESC\nLIMIT 100;"
    }
   ]
  },
  {
   "title": "Users",
   "type": "stat",
   "description": "Users list that runs this query",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT array_agg(u.usename)::TEXT\nFROM pg_stat_statements s LEFT OUTER JOIN pg_user u ON s.userid = u.usesysid\nWHERE dbid = (SELECT oid FROM pg_database WHERE datname = '${datname}') AND queryid = '$query';"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 15, "w": 2, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT * FROM pg_stat_statements WHERE dbid = (SELECT oid FROM pg_database WHERE datname = '${datname}') AND queryid = '$query' ORDER BY calls DESC LIMIT 1;"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 15, "w": 2, "x": 14, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT * FROM pg_stat_statements WHERE dbid = (SELECT oid FROM pg_database WHERE datname = '${datname}') AND queryid = '$query' ORDER BY calls DESC LIMIT 1;"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 15, "w": 3, "x": 16, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT * FROM pg_stat_statements WHERE dbid = (SELECT oid FROM pg_database WHERE datname = '${datname}') AND queryid = '$query' ORDER BY calls DESC LIMIT 1;"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 15, "w": 5, "x": 19, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT * FROM pg_stat_statements WHERE dbid = (SELECT oid FROM pg_database WHERE datname = '${datname}') AND queryid = '$query' ORDER BY calls DESC LIMIT 1;"
    }
   ]
  },
  {
   "title": "Query String",
   "type": "marcusolsson-dynamictext-panel",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 7 },
   "options": {
    "content": "<pre style=\"word-wrap: break-word; font-family: monospace,Consolas,Monaco,Lucida Console,Liberation Mono,DejaVu Sans Mono,Bitstream Vera Sans Mono,Courier New, monospace;\"><code class=\"language-sql\">{{ query }}</pre></blockquote>"
   },
   "targets": [
    {
     "rawSql": "SELECT * FROM pg_stat_statements WHERE dbid = (SELECT oid FROM pg_database WHERE datname = '${datname}') AND queryid = '$query' LIMIT 1;"
    }
   ]
  },
  {
   "title": "QPS (1m)",
   "type": "timeseries",
   "description": "Queries per second according to \n`pg_stat_statements`.`calls`\nin last minute",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(pg_query_calls{ins=\"$ins\", datname=\"$datname\", query=\"$query\"}[1m])",
     "legendFormat": "QPS"
    }
   ]
  },
  {
   "title": "RT (1m)",
   "type": "timeseries",
   "description": "Average Query Latency according to `pg_stat_statements`: rate of `total_exec_time` / rate of `calls` in last minute",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(pg_query_exec_time{ins=\"$ins\", datname=\"$datname\", query=\"$query\"}[1m]) /\n rate(pg_query_calls{ins=\"$ins\", datname=\"$datname\", query=\"$query\"}[1m])",
     "legendFormat": "RT"
    }
   ]
  },
  {
   "title": "Statement Detail",
   "type": "table",
   "description": "It may have multiple records if the same query is executed by multiple different users.",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {
     "legendFormat": "__auto",
     "rawSql": "SELECT queryid::TEXT AS qid, d.datname, r.rolname, s.*\nFROM pg_stat_statements s\n         LEFT JOIN pg_database d ON s.dbid = d.oid\n         LEFT JOIN pg_roles r ON s.userid = r.oid\nWHERE datname='$datname' and queryid = '$query'\nORDER BY mean_exec_time DESC\nLIMIT 100;"
    }
   ]
  },
  {
   "title": "Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "collapsed": true,
   "panels": [
    {
     "title": "Top SQL by RT",
     "type": "table",
     "description": "pg_stat_statements of database ${datname}, order by mean_exec_time DESC.",
     "gridPos": { "h": 18, "w": 24, "x": 0, "y": 32 },
     "targets": [
      {
       "legendFormat": "__auto",
       "rawSql": "SELECT queryid::TEXT AS qid, d.datname, r.rolname, s.*\nFROM pg_stat_statements s\n         LEFT JOIN pg_database d ON s.dbid = d.oid\n         LEFT JOIN pg_roles r ON s.userid = r.oid\nWHERE datname='$datname'\nORDER BY mean_exec_time DESC\nLIMIT 100;"
      }
     ]
    }
   ]
  }
 ]
}