{
 "title": "PGSQL Activity",
 "description": "PostgreSQL Queries for single Instance",
 "tags": [
  "Pigsty",
  "PGSQL",
  "Cluster"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "cls", "label": "Cluster", "query": { "query": "label_values(pg_up, cls)" } },
   {
    "name": "primary",
    "label": "Primary",
    "query": {
     "query": "label_values(pg:cls:leader{cls=\"$cls\"}, ins)"
    }
   },
   {
    "name": "members",
    "label": "Primary",
    "query": {
     "query": "label_values(pg_up{cls=\"$cls\"}, ip)"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "frame": {
      "fields": [
       {
        "config": {},
        "name": "Cluster",
        "type": "string",
        "values": [ "${cls}" ]
       }
      ],
      "meta": {},
      "name": ""
     }
    },
    {
     "frame": {
      "fields": [
       {
        "config": {},
        "name": "Leader",
        "type": "string",
        "values": [ "$primary" ]
       }
      ],
      "meta": {},
      "name": ""
     }
    }
   ]
  },
  {
   "type": "state-timeline",
   "gridPos": { "h": 4, "w": 16, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "sum by (cls,proxy) (haproxy_server_status{proxy=~\"$cls-.*\", state=\"UP\"}) > bool 0",
     "legendFormat": "{{ proxy }}"
    }
   ]
  },
  { "title": "Load", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Postgres Load 1m",
   "type": "timeseries",
   "description": "Overall pressure for this PostgreSQL Node and Instance. \nmax(node:ins:cpu_usage, pg:ins:load, pgbouncer:ins:load)",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "pg:cls:load1{cls=\"$cls\"}",
     "legendFormat": "cluster"
    },
    {
     "expr": "pg:ins:load1{cls=\"$cls\", ins=\"$primary\"}",
     "legendFormat": "{{ ins }} ⭐️"
    },
    {
     "expr": "pg:ins:load1{cls=\"$cls\", ins!=\"$primary\"}",
     "legendFormat": "{{ ins }}"
    }
   ]
  },
  {
   "title": "CPU Usage 1m",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "pg:cls:cpu_usage_1m{cls=\"$cls\"}",
     "legendFormat": "cluster"
    },
    {
     "expr": "pg:ins:cpu_usage_1m{cls=\"$cls\", ins=\"$primary\"}",
     "legendFormat": "{{ ins }} ⭐️"
    },
    {
     "expr": "pg:ins:cpu_usage_1m{cls=\"$cls\", ins!=\"$primary\"}",
     "legendFormat": "{{ ins }}"
    }
   ]
  },
  {
   "title": "Read/Write Bandwidth",
   "type": "timeseries",
   "description": "▲ for read bandwidth, ▼ for write bandwidth",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "pg_up{cls=\"$cls\"} * 0 + on(ip) node:ins:disk_read_bytes_rate1m",
     "legendFormat": "▲{{ ins }}"
    },
    {
     "expr": "pg_up{cls=\"$cls\"} * 0 - on(ip) node:ins:disk_write_bytes_rate1m",
     "legendFormat": "▼{{ ins }}"
    }
   ]
  },
  {
   "title": "Transmit/Receive Bandwidth (Interface)",
   "type": "timeseries",
   "description": "▲ for transmit (out) and ▼ for receive (in)",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "node:ins:network_tx_bytes_rate1m{ip=~\"$members\"}",
     "legendFormat": "▲{{ ins }}"
    },
    {
     "expr": "- node:ins:network_rx_bytes_rate1m{ip=~\"$members\"}",
     "legendFormat": "▼{{ ins }}"
    }
   ]
  },
  { "title": "Sessions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Postgres Conn Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "pg:db:conn_usage{cls=\"$cls\", datname!~'postgres|template\\\\d'}",
     "legendFormat": "{{ ins }}.{{ datname }}"
    }
   ]
  },
  {
   "title": "Pgbouncer Conn Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "pgbouncer:db:conn_usage{cls=\"$cls\", datname!~'pgbouncer|template\\\\d'}",
     "legendFormat": "{{ ins }}.{{ datname }}"
    }
   ]
  },
  {
   "title": "Postgres Backends",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "targets": [
    {
     "expr": "sum by (ins) (pg_activity_count{cls=\"$cls\"})",
     "legendFormat": "{{ datname }}"
    }
   ]
  },
  {
   "title": "Postgres Backends (Stacked)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
   "targets": [
    {
     "expr": "sum by (ins) (pg_activity_count{cls=\"$cls\"})",
     "legendFormat": "{{ datname }}"
    }
   ]
  },
  {
   "title": "Pgbouncer Clients",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 39 },
   "targets": [
    {
     "expr": "pgbouncer:ins:active_clients{cls=\"$cls\"}",
     "legendFormat": "{{ ins }}"
    }
   ]
  },
  {
   "title": "Pgbouncer Waiting Clients",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 39 },
   "targets": [
    {
     "expr": "pgbouncer:ins:waiting_clients{cls=\"$cls\"}",
     "legendFormat": "{{ ins }}"
    }
   ]
  },
  {
   "title": "HAproxy Backends (Database Server)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
   "targets": [
    {
     "expr": "sum by (server) (haproxy_server_current_sessions{ip=~\"$members\"})",
     "legendFormat": "{{ server }}"
    }
   ]
  },
  {
   "title": "Proxy ➔ Server Sessions",
   "type": "timeseries",
   "description": "Session by postgres instance",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (ins,server) (haproxy_server_current_sessions{ip=~\"$members\"})",
     "legendFormat": "{{ ins }} ➔ {{ server }}"
    }
   ]
  },
  {
   "title": "HAproxy Frontents (Proxy Instance)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 54 },
   "targets": [
    {
     "expr": "sum by (ins) (haproxy_server_current_sessions{ip=~\"$members\"})",
     "legendFormat": "{{ ins }}"
    }
   ]
  },
  { "title": "Xacts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 62 } },
  {
   "title": "Cluster Xact Commit Rate",
   "type": "timeseries",
   "description": "Postgres transactions per second according to last 1m, 5m, 15m",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "pg:cls:xact_commit_rate1m{cls=\"$cls\"}",
     "legendFormat": "1m"
    },
    {
     "expr": "pg:cls:xact_commit_rate5m{cls=\"$cls\"}",
     "legendFormat": "5m"
    },
    {
     "expr": "pg:cls:xact_commit_rate15m{cls=\"$cls\"}",
     "legendFormat": "15m"
    }
   ]
  },
  {
   "title": "Cluster Xact Rollback",
   "type": "timeseries",
   "description": "Postgres rollbacked transactions per second according to last 1m, 5m, 15m",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "pg:cls:xact_rollback_rate1m{cls=\"$cls\"}",
     "legendFormat": "1m"
    },
    {
     "expr": "pg:cls:xact_rollback_rate5m{cls=\"$cls\"}",
     "legendFormat": "5m"
    },
    {
     "expr": "pg:cls:xact_rollback_rate15m{cls=\"$cls\"}",
     "legendFormat": "15m"
    }
   ]
  },
  {
   "title": "Transaction RT (avg1m)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "pg:cls:active_time_rate1m{cls=\"$cls\"} / pg:cls:xact_total_rate1m{cls=\"$cls\"}",
     "legendFormat": "Cluster"
    }
   ]
  },
  {
   "title": "Transaction RT (avg1m)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "pg:ins:active_time_rate1m{cls=\"$cls\"} / pg:ins:xact_total_rate15m{cls=\"$cls\"}",
     "legendFormat": "{{ ins }}"
    }
   ]
  },
  {
   "title": "Transaction Commit by Instances",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (ins) (pg:ins:xact_commit_rate1m{cls=\"$cls\", ins=\"$primary\"})",
     "legendFormat": "{{ ins }} ⭐️"
    },
    {
     "expr": "sum by (ins) (pg:ins:xact_commit_rate1m{cls=\"$cls\", ins!=\"$primary\"})",
     "legendFormat": "{{ ins }}"
    }
   ]
  },
  {
   "title": "Transaction Commit by Database",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (datname) (pg:db:xact_commit_rate1m{cls=\"$cls\"})",
     "legendFormat": "{{ datname }}"
    }
   ]
  },
  {
   "title": "Transaction Commit by Instances (Stacked)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 90 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (ins) (pg:db:xact_commit_rate1m{cls=\"$cls\"})",
     "legendFormat": "{{ datname }}"
    }
   ]
  },
  {
   "title": "Transaction Commit by Database (Stacked)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 90 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (datname) (pg:db:xact_commit_rate1m{cls=\"$cls\"})",
     "legendFormat": "{{ datname }}"
    }
   ]
  },
  {
   "title": "Cluster TPS (Pgbouncer)",
   "type": "timeseries",
   "description": "Pgbouncer transactions per second according to last 1m, 5m, 15m",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 99 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "pgbouncer:cls:xact_rate1m{cls=\"$cls\"}",
     "legendFormat": "1m"
    },
    {
     "expr": "pgbouncer:cls:xact_rate5m{cls=\"$cls\"}",
     "legendFormat": "5m"
    },
    {
     "expr": "pgbouncer:cls:xact_rate15m{cls=\"$cls\"}",
     "legendFormat": "15m"
    }
   ]
  },
  {
   "title": "Cluster Xact RT (Pgbouncer)",
   "type": "timeseries",
   "description": "Pgbouncer average transaction response time in last 1m, 5m, 15m",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 99 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "pgbouncer:cls:xact_rt_1m{cls=\"$cls\"}",
     "legendFormat": "1m"
    },
    {
     "expr": "pgbouncer:cls:xact_rt_5m{cls=\"$cls\"}",
     "legendFormat": "5m"
    },
    {
     "expr": "pgbouncer:cls:xact_rt_15m{cls=\"$cls\"}",
     "legendFormat": "15m"
    }
   ]
  },
  { "title": "Queries", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 109 } },
  {
   "title": "Cluster QPS",
   "type": "timeseries",
   "description": "Pgbouncer Queries per second according to last 1m, 5m, 15m",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 110 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "pgbouncer:cls:query_rate1m{cls=\"$cls\"}",
     "legendFormat": "1m"
    },
    {
     "expr": "pgbouncer:cls:query_rate5m{cls=\"$cls\"}",
     "legendFormat": "5m"
    },
    {
     "expr": "pgbouncer:cls:query_rate15m{cls=\"$cls\"}",
     "legendFormat": "15m"
    }
   ]
  },
  {
   "title": "Cluster Query RT",
   "type": "timeseries",
   "description": "Pgbouncer query average response time in last 1m, 5m, 15m",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 110 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "pgbouncer:cls:query_rt_1m{cls=\"$cls\"}",
     "legendFormat": "1m"
    },
    {
     "expr": "pgbouncer:cls:query_rt_5m{cls=\"$cls\"}",
     "legendFormat": "5m"
    },
    {
     "expr": "pgbouncer:cls:query_rt_15m{cls=\"$cls\"}",
     "legendFormat": "15m"
    }
   ]
  },
  {
   "title": "Leader ${primary} QPS",
   "type": "timeseries",
   "description": "Pgbouncer Queries per second according to last 1m, 5m, 15m",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 120 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "pgbouncer:ins:query_rate1m{ins=\"$primary\"}",
     "legendFormat": "1m"
    },
    {
     "expr": "pgbouncer:ins:query_rate5m{ins=\"$primary\"}",
     "legendFormat": "5m"
    },
    {
     "expr": "pgbouncer:ins:query_rate15m{ins=\"$primary\"}",
     "legendFormat": "15m"
    }
   ]
  },
  {
   "title": "Leader ${primary} Query RT",
   "type": "timeseries",
   "description": "Pgbouncer query average response time in last 1m, 5m, 15m",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 120 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "pgbouncer:ins:query_rt_1m{ins=\"$primary\"}",
     "legendFormat": "1m"
    },
    {
     "expr": "pgbouncer:ins:query_rt_5m{ins=\"$primary\"}",
     "legendFormat": "5m"
    },
    {
     "expr": "pgbouncer:ins:query_rt_15m{ins=\"$primary\"}",
     "legendFormat": "15m"
    }
   ]
  },
  {
   "title": "QPS by Instance",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 128 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "pgbouncer:cls:query_rate5m{cls=\"$cls\"}",
     "legendFormat": "Cluster"
    },
    {
     "expr": "pgbouncer:ins:query_rate5m{cls=\"$cls\"}",
     "legendFormat": "{{ ins }}"
    }
   ]
  },
  {
   "title": "Query RT by Instance",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 128 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "pgbouncer:cls:query_rt_1m{cls=\"$cls\"}",
     "legendFormat": "Cluster"
    },
    {
     "expr": "pgbouncer:ins:query_rt_1m{cls=\"$cls\"}",
     "legendFormat": "{{ ins }}"
    }
   ]
  }
 ]
}