{
 "title": "PGSQL Xacts",
 "description": "PostgreSQL Transaction detail for instance",
 "tags": [
  "Pigsty",
  "PGSQL",
  "Instance"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "ins", "label": "Instance", "query": { "query": "label_values(pg_up, ins)" } },
   {
    "name": "ip",
    "label": "IP",
    "query": {
     "query": "label_values(pg_up{ins=\"$ins\"} , instance)"
    }
   },
   {
    "name": "seq",
    "label": "Sequence",
    "query": {
     "query": "label_values(pg_up{ins=\"$ins\"},  ins)"
    }
   },
   {
    "name": "cls",
    "label": "Cluster",
    "query": {
     "query": "label_values(pg_up{ins=\"$ins\"}, cls)"
    }
   },
   {
    "name": "node",
    "label": "Node",
    "query": {
     "query": "label_values(node_uname_info{ins=\"$ins\"}, nodename)"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "frame": {
      "fields": [
       {
        "config": {},
        "name": "Instance",
        "type": "string",
        "values": [ "$ins" ]
       }
      ],
      "meta": {},
      "name": ""
     }
    },
    {
     "frame": {
      "fields": [
       {
        "config": {},
        "name": "Cluster",
        "type": "string",
        "values": [ "${cls}" ]
       }
      ],
      "meta": {},
      "name": ""
     }
    },
    {
     "frame": {
      "fields": [
       {
        "config": {},
        "name": "Node IP",
        "type": "string",
        "values": [ "${ip}" ]
       }
      ],
      "meta": {},
      "name": ""
     }
    },
    {
     "frame": {
      "fields": [
       {
        "config": {},
        "name": "Hostname",
        "type": "string",
        "values": [ "${node}" ]
       }
      ],
      "meta": {}
     }
    }
   ]
  },
  {
   "title": "Postgres Instances",
   "type": "table",
   "description": "All instances among pgsql cluster ${cls}\n\nInstance: Goto PGSQL Instance\n\nIP: Goto PGSQL Node\n\nStatus: Goto PGSQL Service\n\nLoad: max(cpu,postgres,pgbouncer)\n\nSpace: Disk space usage max(all device)\n\nProxy: session number, Goto Haproxy Admin Page",
   "gridPos": { "h": 7, "w": 18, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "pg_in_recovery{cls=\"$cls\"}"
    },
    {
     "expr": "ins:pressure1{cls=\"$cls\"}"
    },
    {
     "expr": "sum by (ins) (pg:ins:xact_total_rate1m{cls=\"$cls\"})"
    },
    {
     "expr": "max by (ins) (pg:ins:num_backends{cls=\"$cls\"})"
    },
    {
     "expr": "max by (ins) (pgbouncer:ins:xact_rt_1m{cls=\"$cls\"})"
    },
    {
     "expr": "max by (ins) (pg:ins:conn_usage{cls=\"$cls\"})"
    },
    {
     "expr": "sum by (ins) (pgbouncer:ins:query_rate1m{cls=\"$cls\"})"
    },
    {
     "expr": "sum by (ins) (pgbouncer:ins:waiting_clients{cls=\"$cls\"})"
    },
    {
     "expr": "max by (ins) (pg:ins:lag_bytes{cls=\"$cls\", ins=~'$cls.*'})"
    },
    {
     "expr": "min by (ins) (up{cls=\"$cls\", job=\"pgsql\"})"
    }
   ]
  },
  { "title": "Postgres Xacts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Transaction Commit",
   "type": "timeseries",
   "description": "Pgbouncer transactions per second according to last 1m, 5m, 15m",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "pg:ins:xact_commit_rate1m{ins=\"$ins\"}",
     "legendFormat": "1m"
    },
    {
     "expr": "pg:ins:xact_commit_rate5m{ins=\"$ins\"}",
     "legendFormat": "5m"
    },
    {
     "expr": "pg:ins:xact_commit_rate15m{ins=\"$ins\"}",
     "legendFormat": "15m"
    }
   ]
  },
  {
   "title": "Transaction Rollback",
   "type": "timeseries",
   "description": "postgres rollbacked transactions per second according to last 1m, 5m, 15m",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "pg:ins:xact_rollback_rate1m{ins=\"$ins\"}",
     "legendFormat": "1m"
    },
    {
     "expr": "pg:ins:xact_rollback_rate1m{ins=\"$ins\"}",
     "legendFormat": "5m"
    },
    {
     "expr": "pg:ins:xact_rollback_rate1m{ins=\"$ins\"}",
     "legendFormat": "15m"
    }
   ]
  },
  {
   "title": "TPS Variation σ/µ (5m) ",
   "type": "timeseries",
   "description": "coefficient of variation, CV of TPS in last 5 minutes",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "stddev_over_time(pg:ins:xact_commit_rate1m{ins=\"$ins\"}[5m])/\navg_over_time(pg:ins:xact_commit_rate1m{ins=\"$ins\"}[5m])",
     "legendFormat": "QPS CV"
    }
   ]
  },
  {
   "title": "Rollback Ratio",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "pg:ins:xact_rollback_rate1m{ins=\"$ins\"}",
     "legendFormat": "Rollback Rate"
    }
   ]
  },
  {
   "title": "Transaction Commit by Database",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "pg:db:xact_commit_rate1m{ins=\"$ins\"}",
     "legendFormat": "{{ datname }}"
    }
   ]
  },
  {
   "title": "SAGE",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (state) (pg_activity_max_tx_duration{ins=\"$ins\", state!~\"(idle.*|disabled)\"})",
     "legendFormat": "{{ state }}"
    }
   ]
  },
  { "title": "Locks", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "Locks Count",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (ins) (pg_lock_count{ins=\"$ins\"})",
     "legendFormat": "Locks"
    }
   ]
  },
  {
   "title": "Locks",
   "type": "timeseries",
   "gridPos": { "h": 17, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (mode) (pg_lock_count{ins=\"$ins\"})",
     "legendFormat": "{{ mode }}"
    }
   ]
  },
  {
   "title": "Locks by Category",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "pg:ins:xlock_count{ins=\"$ins\"}",
     "legendFormat": "Exclusive"
    },
    {
     "expr": "pg:ins:wlock_count{ins=\"$ins\"}",
     "legendFormat": "Write"
    },
    {
     "expr": "pg:ins:rlock_count{ins=\"$ins\"}",
     "legendFormat": "Read"
    }
   ]
  },
  { "title": "Pgbouncer Transactions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 } },
  {
   "title": "TPS Seasonality",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "pgbouncer:ins:xact_rate5m{ins=\"$ins\"}",
     "legendFormat": "TPS"
    },
    {
     "expr": "pgbouncer:ins:xact_rate5m{ins=\"$ins\"} OFFSET 1d",
     "legendFormat": "Yesterday"
    },
    {
     "expr": "pgbouncer:ins:xact_rate5m{ins=\"$ins\"} OFFSET 2d",
     "legendFormat": "2 Day Ago"
    }
   ]
  },
  {
   "title": "Average Queries per Xact",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "pgbouncer:ins:query_rate1m{ins=\"$ins\"} / pgbouncer:ins:xact_rate1m{ins=\"$ins\"}",
     "legendFormat": "Q"
    }
   ]
  },
  {
   "title": "TPS",
   "type": "timeseries",
   "description": "Pgbouncer transactions per second according to last 1m, 5m, 15m",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "pgbouncer:ins:xact_rate1m{ins=\"$ins\"}",
     "legendFormat": "1m"
    },
    {
     "expr": "pgbouncer:ins:xact_rate5m{ins=\"$ins\"}",
     "legendFormat": "5m"
    },
    {
     "expr": "pgbouncer:ins:xact_rate15m{ins=\"$ins\"}",
     "legendFormat": "15m"
    }
   ]
  },
  {
   "title": "Xact RT",
   "type": "timeseries",
   "description": "Pgbouncer average transaction response time in last 1m, 5m, 15m",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "pgbouncer:ins:xact_rt_1m{ins=\"$ins\"}",
     "legendFormat": "1m"
    },
    {
     "expr": "pgbouncer:ins:xact_rt_5m{ins=\"$ins\"}",
     "legendFormat": "5m"
    },
    {
     "expr": "pgbouncer:ins:xact_rt_15m{ins=\"$ins\"}",
     "legendFormat": "15m"
    }
   ]
  },
  {
   "title": "Pgbouncer TPS Variation σ/µ (5m) ",
   "type": "timeseries",
   "description": "coefficient of variation, CV of Pgbouncer TPS in last 5 minutes",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "stddev_over_time(pgbouncer:ins:xact_rate1m{ins=\"$ins\"}[5m])/\navg_over_time(pgbouncer:ins:xact_rate1m{ins=\"$ins\"}[5m])",
     "legendFormat": "QPS CV"
    }
   ]
  },
  {
   "title": "Pgbouncer RT Variation σ/µ (5m) ",
   "type": "timeseries",
   "description": "coefficient of variation, CV of Pgbouncer Xact RT in last 5 minutes",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "stddev_over_time(pgbouncer:ins:xact_rt_5m{ins=\"$ins\"}[5m])/\navg_over_time(pgbouncer:ins:xact_rt_5m{ins=\"$ins\"}[5m])",
     "legendFormat": "QPS CV"
    }
   ]
  },
  {
   "title": "TPS Distribution",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg_over_time(pgbouncer:ins:xact_rate1m{ins=\"$ins\"}[15m]) + 3 * stddev_over_time(pgbouncer:ins:xact_rate1m{ins=\"$ins\"}[15m])",
     "legendFormat": "+3σ"
    },
    {
     "expr": "avg_over_time(pgbouncer:ins:xact_rate1m{ins=\"$ins\"}[15m]) - 3 * stddev_over_time(pgbouncer:ins:xact_rate1m{ins=\"$ins\"}[15m])",
     "legendFormat": "-3σ"
    },
    {
     "expr": "avg_over_time(pgbouncer:ins:xact_rate1m{ins=\"$ins\"}[15m]) + stddev_over_time(pgbouncer:ins:xact_rate1m{ins=\"$ins\"}[15m])",
     "legendFormat": "+σ"
    },
    {
     "expr": "avg_over_time(pgbouncer:ins:xact_rate1m{ins=\"$ins\"}[15m]) - stddev_over_time(pgbouncer:ins:xact_rate1m{ins=\"$ins\"}[15m])",
     "legendFormat": "-σ"
    },
    {
     "expr": "avg_over_time(pgbouncer:ins:xact_rate1m{ins=\"$ins\"}[15m])",
     "legendFormat": "µ"
    },
    {
     "expr": "pgbouncer:ins:xact_rate1m{ins=\"$ins\"}",
     "legendFormat": "QPS"
    }
   ]
  },
  {
   "title": "RT Distribution",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg_over_time(pgbouncer:ins:xact_rt_1m{ins=\"$ins\"}[15m]) + 3 * stddev_over_time(pgbouncer:ins:xact_rt_1m{ins=\"$ins\"}[15m])",
     "legendFormat": "+3σ"
    },
    {
     "expr": "avg_over_time(pgbouncer:ins:xact_rt_1m{ins=\"$ins\"}[15m]) - 3 * stddev_over_time(pgbouncer:ins:xact_rt_1m{ins=\"$ins\"}[15m]) ",
     "legendFormat": "-3σ"
    },
    {
     "expr": "avg_over_time(pgbouncer:ins:xact_rt_1m{ins=\"$ins\"}[15m]) + stddev_over_time(pgbouncer:ins:xact_rt_1m{ins=\"$ins\"}[15m])",
     "legendFormat": "+σ"
    },
    {
     "expr": "avg_over_time(pgbouncer:ins:xact_rt_1m{ins=\"$ins\"}[15m]) - stddev_over_time(pgbouncer:ins:xact_rt_1m{ins=\"$ins\"}[15m])",
     "legendFormat": "-σ"
    },
    {
     "expr": "avg_over_time(pgbouncer:ins:xact_rt_1m{ins=\"$ins\"}[15m])",
     "legendFormat": "µ"
    },
    {
     "expr": "pgbouncer:ins:xact_rt_1m{ins=\"$ins\"}",
     "legendFormat": "v"
    }
   ]
  },
  {
   "title": "TPS by Database",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "pgbouncer:ins:xact_rate5m{ins=\"$ins\"}",
     "legendFormat": "Instance"
    },
    {
     "expr": "pgbouncer:db:xact_rate5m{ins=\"$ins\"}",
     "legendFormat": "{{ datname }}"
    }
   ]
  },
  {
   "title": "TPS by Instance",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "pgbouncer:cls:xact_rate5m{cls=\"$cls\"}",
     "legendFormat": "Cluster"
    },
    {
     "expr": "pgbouncer:ins:xact_rate5m{cls=\"$cls\"}",
     "legendFormat": "{{ ins }}"
    }
   ]
  },
  {
   "title": "Xact RT by Database",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 87 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "pgbouncer:ins:xact_rt_1m{ins=\"$ins\"}",
     "legendFormat": "Instance"
    },
    {
     "expr": "pgbouncer:db:xact_rt_1m{ins=\"$ins\"}",
     "legendFormat": "{{ datname }}"
    }
   ]
  },
  {
   "title": "Xact RT by Instance",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 87 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "pgbouncer:cls:xact_rt_1m{cls=\"$cls\"}",
     "legendFormat": "Cluster"
    },
    {
     "expr": "pgbouncer:ins:xact_rt_1m{cls=\"$cls\"}",
     "legendFormat": "{{ ins }}"
    }
   ]
  }
 ]
}