{
 "title": "PGSQL PITR",
 "description": "PostgreSQL PITR Auxiliary Dashboard",
 "tags": [
  "Pigsty",
  "PGSQL",
  "Cluster"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "cls", "label": "Cluster", "query": { "query": "label_values(pg_up, cls)" } },
   {
    "name": "primary",
    "label": "Primary",
    "query": {
     "query": "label_values(pg:cls:leader{cls=\"$cls\"}, ins)"
    }
   },
   {
    "name": "members",
    "label": "Primary",
    "query": {
     "query": "label_values(pg_up{cls=\"$cls\"}, ip)"
    }
   },
   {
    "name": "node_cls",
    "label": "Node Cluster",
    "query": {
     "query": "label_values(node_load1{ip=~\"$members\"},cls)"
    }
   },
   {
    "name": "instances",
    "label": "Log Ins",
    "query": {
     "query": "label_values(up{cls=\"$cls\"},ins)"
    }
   },
   { "name": "src", "label": "Log Src", "query": "postgres,pgbackrest,patroni" },
   { "name": "search", "label": "Search" }
  ]
 },
 "panels": [
  { "title": "Backup", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Repo Status",
   "type": "table",
   "description": "Current repository status for selected stanzas and repos.",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "pgbackrest_repo_status{ins=\"$primary\", stanza=~\"$cls\"}"
    }
   ]
  },
  {
   "title": "Stanza Status ",
   "type": "table",
   "description": "Current stanza and active operations statuses for selected stanzas.",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "pgbackrest_stanza_status{ins=\"$primary\", stanza=~\"$cls\"}"
    },
    {
     "expr": "pgbackrest_stanza_lock_status{ins=\"$primary\", stanza=~\"$cls\"}"
    },
    {
     "expr": "(pgbackrest_stanza_backup_compete_bytes{ins=\"$primary\", stanza=~\"$cls\"} / \npgbackrest_stanza_backup_total_bytes{ins=\"$primary\", stanza=~\"$cls\"})*100"
    }
   ]
  },
  {
   "title": "Backup Details",
   "type": "table",
   "description": "Backup detail info for selected stanzas, repos, backup types, block incremental statuses and backup names.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "pgbackrest_backup_info{ins=\"$primary\",stanza=~\"$cls\"}"
    }
   ]
  },
  { "title": "PITR", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "XID Progress",
   "type": "timeseries",
   "description": "TransactionID xmax on each instance",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "pg_xact_xmax{cls=\"$cls\"}",
     "legendFormat": "{{ ins }}"
    }
   ]
  },
  {
   "title": "LSN Progress",
   "type": "timeseries",
   "description": "Current WAL Sequence Number on each Instance",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "hex" } },
   "targets": [
    {
     "expr": "pg_lsn{cls=\"$cls\"}",
     "legendFormat": "{{ ins }}"
    }
   ]
  },
  { "title": "Member", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Postgres & Patroni PITR Status",
   "type": "table",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "max by (ins) (patroni_primary{cls=\"$cls\"}) + \nmax by (ins) (patroni_standby_leader{cls=\"$cls\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by (ins) (pg_checkpoint_tli{cls=\"$cls\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by (ins) (pg_xact_xmax{cls=\"$cls\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by (ins) (patroni_is_paused{cls=\"$cls\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by (ins) (pg_lsn{cls=\"$cls\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "count by (ins) (pg_repl_lsn{cls=\"$cls\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by (ins,state) (pg_recv_flush_tli{cls=\"$cls\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by (ins) (patroni_xlog_paused{cls=\"$cls\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by (ins) (patroni_postgres_running{cls=\"$cls\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "pg_checkpoint_tli{cls=\"$cls\"} < bool on(cls) group_left() max by (cls)(pg_checkpoint_tli{cls=\"$cls\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by (ins) (time() - patroni_postmaster_start_time{cls=\"$cls\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by (ins) (patroni_up{cls=\"$cls\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "min by (ins,ip) (pg_up{cls=\"$cls\", job=\"pgsql\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "min by (ins) (pg_in_recovery{cls=\"$cls\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "stat",
   "description": "Blue  = PostgreSQL\n\nGreen = Pgbouncer\n\nYellow : Agent (Patroni / PG Exporters)",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "pg_up{ip=~\"$members\"}",
     "legendFormat": "postgres {{ ins }}"
    },
    {
     "expr": "pgbouncer_up{ip=~\"$members\"}",
     "legendFormat": "pgbouncer {{ ins }}"
    },
    {
     "expr": "patroni_up{ip=~\"$members\"}",
     "legendFormat": "patroni {{ ins }}"
    },
    {
     "expr": "pg_exporter_agent_up{ip=~\"$members\"}",
     "legendFormat": "pg_exporter {{ ins }}"
    },
    {
     "expr": "pgbouncer_exporter_agent_up{ip=~\"$members\"}",
     "legendFormat": "pgb_exporter {{ ins }}"
    },
    {
     "expr": "node_up{ip=~\"$members\"}",
     "legendFormat": "node {{ ins }}"
    },
    {
     "expr": "haproxy_up{ip=~\"$members\"}",
     "legendFormat": "haproxy {{ ins }}"
    },
    {
     "expr": "docker_up{ip=~\"$members\"}",
     "legendFormat": "docker {{ ins }}"
    },
    {
     "expr": "promtail_up{ip=~\"$members\"}",
     "legendFormat": "promtail {{ ins }}"
    },
    {
     "expr": "infra_up{ip=~\"$members\"}",
     "legendFormat": "{{ ins }}"
    },
    {
     "expr": "etcd_up{ip=~\"$members\"}",
     "legendFormat": "{{ ins }}"
    },
    {
     "expr": "redis_up{ip=~\"$members\"}",
     "legendFormat": "{{ ins }}"
    },
    {
     "expr": "minio_up{ip=~\"$members\"}",
     "legendFormat": "{{ ins }}"
    },
    {
     "expr": "mongo_up{ip=~\"$members\"}",
     "legendFormat": "{{ ins }}"
    },
    {
     "expr": "mysql_up{ip=~\"$members\"}",
     "legendFormat": "mysql {{ ins }}"
    },
    {
     "expr": "mysql_exporter_up{ip=~\"$members\"}",
     "legendFormat": "mysql_exporter"
    }
   ]
  },
  {
   "title": "Replication",
   "type": "table",
   "description": "Replication Status among cluster ${cls}",
   "gridPos": { "h": 6, "w": 16, "x": 0, "y": 31 },
   "targets": [
    {
     "expr": "pg:cls:sender{cls=\"$cls\"}"
    },
    {
     "expr": "pg:cls:receiver{cls=\"$cls\"}"
    }
   ]
  },
  {
   "type": "stat",
   "description": "Blue  = PostgreSQL\n\nGreen = Pgbouncer\n\nYellow : Agent (Patroni / PG Exporters)",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 31 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_checkpoint_tli{cls=\"$cls\"} < bool on(cls) group_left() \nmax by (cls)(pg_checkpoint_tli{cls=\"$cls\"})",
     "legendFormat": "{{ ins }}"
    }
   ]
  },
  { "title": "Leadership", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  {
   "title": "Timeline",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 16, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "pg_checkpoint_tli{cls=\"$cls\"}",
     "legendFormat": "{{ ins }}"
    }
   ]
  },
  {
   "title": "Leadership",
   "type": "timeseries",
   "description": "Leadership shows who is in charge of this cluster ${cls}",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "(pg_in_recovery{cls=\"$cls\"} == 0) * 0 + 1",
     "legendFormat": "{{ ins }}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "pg:cls:leader{cls=\"$cls\"}",
     "legendFormat": "{{ ins }}"
    }
   ]
  },
  { "title": "Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "Logs (5m)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum by (cls,src) (count_over_time(({cls=\"$cls\", src=\"postgres\"})[5m]))",
     "legendFormat": "{{ src }}"
    },
    {
     "expr": "sum by (cls,src) (count_over_time(({cls=\"$cls\", src=\"patroni\"})[5m]))",
     "legendFormat": "{{ src }}"
    },
    {
     "expr": "sum by (cls,src)(count_over_time(({cls=\"$cls\", src=\"pgbackrest\"})[5m]))",
     "legendFormat": "pgbackrest"
    }
   ]
  },
  {
   "title": "Logs per $__interval",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 3, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (cls,src) (count_over_time(({cls=\"$cls\", src=\"postgres\"})[$__interval]))",
     "legendFormat": "{{ src }}"
    },
    {
     "expr": "sum by (cls,src) (count_over_time(({cls=\"$cls\", src=\"patroni\"})[$__interval]))",
     "legendFormat": "{{ src }}"
    },
    {
     "expr": "sum by (cls,src) (sum(count_over_time(({cls=\"$cls\", src=\"pgbackrest\"})[$__interval])))",
     "legendFormat": "pgbackrest"
    }
   ]
  },
  {
   "title": "Searched Logs per $__interval",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 13, "x": 11, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(count_over_time(({cls=\"$cls\", job=\"pgsql\", ins=~\"$instances\", src=~\"$src\"} |~ \"$search\")[$__interval]))",
     "legendFormat": "log rate"
    }
   ]
  },
  {
   "title": "${src} logs",
   "type": "logs",
   "description": "Recent logs for pgbouncer & patroni & postgres",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 51 },
   "targets": [
    {
     "expr": "{cls=\"$cls\", job=\"pgsql\", ins=~\"$instances\", src=~\"$src\"} |~ \"$search\""
    }
   ]
  },
  { "title": "Docs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 63 } },
  {
   "title": "PITR Docs",
   "type": "text",
   "gridPos": { "h": 33, "w": 24, "x": 0, "y": 64 },
   "options": {
    "content": "[Pigsty Backup & Restore Documentation](https://doc.pgsty.com/pgsql/backup/restore/): https://doc.pgsty.com/pgsql/backup/restore/\n\n\n### By Time\n\nThe most frequently used target is the time point; you can specify the time point to restore to:\n\n```bash title=\"restore to a timepoint\"\n./pgsql-pitr.yml -l ${cls} -e '{\"pg_pitr\": { \"time\": \"2025-07-13 10:00:00+00\" }}'\n```\n\nTime should be a valid PostgreSQL [`TIMESTAMP`](https://www.postgresql.org/docs/17/datatype-datetime.html#DATATYPE-DATETIME-INPUT-TIME-STAMPS), `YYYY-MM-DD HH:MM:SS+TZ` is recommended.\n\n\n### By Name\n\nYou can create a named restore point with [`pg_create_restore_point`](https://www.postgresql.org/docs/current/functions-admin.html#id-1.5.8.34.5.5.2.2.1.1.1.1):\n\n```sql\nSELECT pg_create_restore_point('shit_incoming');\n```\n\nAnd use that named restore point in PITR:\n\n```bash\n./pgsql-pitr.yml -l ${cls} -e '{\"pg_pitr\": { \"name\": \"shit_incoming\" }}'\n```\n\n\n### By XID\n\nIf you have a transaction that accidentally deleted some data, the best way to recover is to restore the database to the state before that transaction.\n\n```bash title=\"restore right before a transaction\"\n./pgsql-pitr.yml -l ${cls} -e '{\"pg_pitr\": { \"xid\": \"250000\", exclusive: true }}'\n```\n\nYou can find the exact transaction id from monitoring dashboard, or find it from `TXID` from the CSVLOG.\n\n\n### By LSN\n\nPostgreSQL uses the [LSN](https://www.postgresql.org/docs/current/datatype-pg-lsn.html) (Log Sequence Number) to identify the position of a WAL record.\nYou can find it everywhere, like the PG LSN panel from Pigsty dashboards.\n\n```bash title=\"restore to a LSN\"\n./pgsql-pitr.yml -l ${cls} -e '{\"pg_pitr\": { \"lsn\": \"0/4001C80\", timeline: \"1\" }}'\n```\n\nTo restore to an exact point in the WAL stream, you may also specify the [`timeline`](https://www.postgresql.org/docs/current/runtime-config-wal.html#RECOVERY-TARGET-TIMELINE) parameter (default to `latest`)"
   }
  }
 ]
}