{
 "title": "CMDB Overview",
 "description": "PostgreSQL Catalog Explorer for Single Instance",
 "tags": [
  "Pigsty",
  "INFRA",
  "Overview"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Meta",
   "type": "stat",
   "gridPos": { "h": 10, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT  key, to_json(value) #>> '{}' AS value FROM pigsty.global_config WHERE key\n    in ('admin_ip', 'version', 'region');"
    }
   ]
  },
  {
   "title": "Portals",
   "type": "table",
   "gridPos": { "h": 10, "w": 9, "x": 5, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT d.key                  AS name,\n       d.value ->> 'domain'   AS domain,\n       replace(d.value ->> 'endpoint', '${admin_ip}', pigsty.get_param('admin_ip') ) AS endpoint\nFROM pigsty.global_config v,\n     jsonb_each(v.value) d\nWHERE v.key = 'infra_portal';"
    }
   ]
  },
  {
   "title": "Groups",
   "type": "table",
   "gridPos": { "h": 10, "w": 4, "x": 14, "y": 1 },
   "targets": [
    { "rawSql": "SELECT cls FROM pigsty.group" }
   ]
  },
  {
   "title": "Infra Nodes",
   "type": "table",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT key AS ip, (value ->> 'infra_seq')::INTEGER AS infra_seq, \n       'infra-' || (value ->> 'infra_seq') AS name\nFROM pigsty.group_config gc, jsonb_each(gc.hosts)\nWHERE cls = 'infra';"
    }
   ]
  },
  {
   "title": "Etcd Cluster",
   "type": "table",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 6 },
   "targets": [
    {
     "rawSql": "SELECT seq, ip, ins FROM pigsty.etcd_instance;"
    }
   ]
  },
  {
   "title": "Nginx",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "Nginx / Repo Address",
     "type": "stat",
     "gridPos": { "h": 13, "w": 5, "x": 0, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "string" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT  key, to_json(value) #>> '{}' AS value FROM pigsty.global_config WHERE key\n    in ('nginx_port', 'nginx_sslmode', 'nginx_home', 'nginx_port', 'nginx_ssl_port', 'repo_name');"
      }
     ]
    },
    {
     "title": "Nginx Navbar",
     "type": "table",
     "gridPos": { "h": 13, "w": 19, "x": 5, "y": 22 },
     "targets": [
      {
       "rawSql": "WITH portals AS (SELECT d.key                  AS name,\n                        d.value ->> 'domain'   AS domain,\n                        d.value ->> 'endpoint' AS endpoint\n                 FROM pigsty.global_config v,\n                      jsonb_each(v.value) d\n                 WHERE v.key = 'infra_portal'),\n     navbar AS (SELECT d ->> 'name'    AS name,\n                       d ->> 'url'     AS domain,\n                       d ->> 'comment' AS comment\n                FROM pigsty.global_config v,\n                     jsonb_array_elements(v.value) d\n                WHERE v.key = 'nginx_navbar')\nSELECT name,comment,case\n   when starts_with(domain, '/') THEN (SELECT 'http://' || domain FROM portals WHERE name = 'home' LIMIT 1) || domain\n   ELSE replace(domain, '${grafana}', (SELECT 'http://' || domain FROM portals WHERE name = 'grafana' LIMIT 1)) END AS url\nFROM navbar;"
      }
     ]
    }
   ]
  },
  {
   "title": "REPO & PKGS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "Repo Upstream",
     "type": "table",
     "gridPos": { "h": 13, "w": 12, "x": 0, "y": 36 },
     "targets": [
      {
       "rawSql": "SELECT d ->> 'name'        AS name,\n       d ->> 'module'      AS module,\n       d -> 'releases'     AS releases,\n       d ->> 'description' AS description,\n       d -> 'baseurl'      AS baseurl\nFROM pigsty.global_config v,\n     jsonb_array_elements(v.value) d\nWHERE v.key = 'repo_upstream';"
      }
     ]
    },
    {
     "title": "Node Packages",
     "type": "table",
     "gridPos": { "h": 4, "w": 12, "x": 12, "y": 36 },
     "targets": [
      {
       "rawSql": "SELECT pkg\nFROM pigsty.global_config v,\n     jsonb_array_elements_text(v.value) pkg\nWHERE v.key = 'node_default_packages'\nUNION ALL\nSELECT pkg\nFROM pigsty.global_config v,\n     jsonb_array_elements_text(v.value) pkg\nWHERE v.key = 'node_packages';"
      }
     ]
    },
    {
     "title": "Infra Packages",
     "type": "table",
     "gridPos": { "h": 4, "w": 12, "x": 12, "y": 40 },
     "targets": [
      {
       "rawSql": "SELECT pkg\nFROM pigsty.global_config v,\n     jsonb_array_elements_text(v.value) pkg\nWHERE v.key = 'infra_packages'\nUNION ALL\nSELECT to_json(value) #>> '{}' AS \"DCS Type\" FROM pigsty.global_config WHERE key = 'infra_packages_pip';"
      }
     ]
    },
    {
     "title": "PGSQL Packages",
     "type": "table",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 44 },
     "targets": [
      {
       "rawSql": "WITH ver AS (SELECT  to_json(value) #>> '{}' AS \"version\" FROM pigsty.global_config WHERE key = 'pg_version' LIMIT 1)\nSELECT replace(pkg, '$v' , (SELECT version FROM ver LIMIT 1))\nFROM pigsty.global_config v, jsonb_array_elements_text(v.value) pkg\nWHERE v.key = 'pg_packages'\nUNION ALL\nSELECT replace(pkg, '$v' , (SELECT version FROM ver LIMIT 1))\nFROM pigsty.global_config v, jsonb_array_elements_text(v.value) pkg\nWHERE v.key = 'pg_extensions'"
      }
     ]
    },
    {
     "title": "Repo Packages",
     "type": "table",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 49 },
     "targets": [
      {
       "rawSql": "SELECT pkg\nFROM pigsty.global_config v,\n     jsonb_array_elements_text(v.value) pkg\nWHERE v.key = 'repo_packages'\nUNION ALL\nSELECT pkg\nFROM pigsty.global_config v,\n     jsonb_array_elements_text(v.value) pkg\nWHERE v.key = 'repo_url_packages';"
      }
     ]
    },
    {
     "title": "PGSQL Extensions",
     "type": "table",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 49 },
     "targets": [
      {
       "rawSql": "WITH ver AS (SELECT  to_json(value) #>> '{}' AS \"version\" FROM pigsty.global_config WHERE key = 'pg_version' LIMIT 1)\nSELECT replace(pkg, '$v' , (SELECT version FROM ver LIMIT 1))\nFROM pigsty.global_config v, jsonb_array_elements_text(v.value) pkg\nWHERE v.key = 'pg_extensions';"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 2, "w": 24, "x": 0, "y": 54 },
     "fieldConfig": { "defaults": { "unit": "string" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT  key, to_json(value) #>> '{}' AS value FROM pigsty.global_config WHERE key\n    in ('repo_modules', 'repo_remove','node_repo_modules', 'node_repo_remove');"
      }
     ]
    }
   ]
  },
  {
   "title": "DNS / Hosts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 57 },
     "fieldConfig": { "defaults": { "unit": "string" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT  to_json(value) #>> '{}' AS \"DNS Enabled\" FROM pigsty.global_config WHERE key = 'dns_enabled';"
      }
     ]
    },
    {
     "title": "DNS Records",
     "type": "table",
     "gridPos": { "h": 8, "w": 7, "x": 4, "y": 57 },
     "targets": [
      {
       "rawSql": "SELECT replace(record, '${admin_ip}', pigsty.get_param('admin_ip'))\nFROM pigsty.global_config v, jsonb_array_elements_text(v.value) record\nWHERE v.key = 'dns_records';"
      }
     ]
    },
    {
     "title": "/etc/resolv.conf",
     "type": "table",
     "gridPos": { "h": 8, "w": 7, "x": 11, "y": 57 },
     "targets": [
      {
       "rawSql": "SELECT replace(record, '${admin_ip}', pigsty.get_param('admin_ip'))\nFROM pigsty.global_config v,\n     jsonb_array_elements_text(v.value) record\nWHERE v.key = 'node_dns_options'\nUNION ALL\nSELECT replace(record, '${admin_ip}', pigsty.get_param('admin_ip'))\nFROM pigsty.global_config v,\n     jsonb_array_elements_text(v.value) record\nWHERE v.key = 'node_dns_servers';"
      }
     ]
    },
    {
     "title": "/etc/hosts",
     "type": "table",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 57 },
     "targets": [
      {
       "rawSql": "SELECT replace(record, '${admin_ip}', pigsty.get_param('admin_ip'))\nFROM pigsty.global_config v,\n     jsonb_array_elements_text(v.value) record\nWHERE v.key = 'node_default_etc_hosts'\nUNION ALL\nSELECT replace(record, '${admin_ip}', pigsty.get_param('admin_ip'))\nFROM pigsty.global_config v,\n     jsonb_array_elements_text(v.value) record\nWHERE v.key = 'node_etc_hosts';"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 61 },
     "fieldConfig": { "defaults": { "unit": "string" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT  to_json(value) #>> '{}' AS \"Node DNS Method\" FROM pigsty.global_config WHERE key = 'node_dns_method';"
      }
     ]
    }
   ]
  },
  {
   "title": "PGSQL Cluster",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "PGSQL Clusters",
     "type": "table",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 66 },
     "targets": [
      {
       "rawSql": "SELECT * FROM pigsty.pg_cluster"
      }
     ]
    }
   ]
  },
  {
   "title": "PGSQL Instance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "PGSQL Instance",
     "type": "table",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 74 },
     "targets": [
      {
       "rawSql": "SELECT * FROM pigsty.pg_instance"
      }
     ]
    }
   ]
  },
  {
   "title": "PGSQL Service",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "PGSQL Service",
     "type": "table",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 84 },
     "targets": [
      {
       "rawSql": "SELECT * FROM pigsty.pg_service;"
      }
     ]
    }
   ]
  },
  {
   "title": "PGSQL Database",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "PGSQL Database",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 95 },
     "targets": [
      {
       "rawSql": "SELECT * FROM pigsty.pg_database;"
      }
     ]
    }
   ]
  },
  {
   "title": "REDIS Cluster",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "PGSQL Clusters",
     "type": "table",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 104 },
     "targets": [
      {
       "rawSql": "SELECT * FROM pigsty.redis_cluster"
      }
     ]
    },
    {
     "title": "REDIS Node",
     "type": "table",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 111 },
     "targets": [
      {
       "rawSql": "SELECT * FROM pigsty.redis_node;"
      }
     ]
    },
    {
     "title": "REDIS Instance",
     "type": "table",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 120 },
     "targets": [
      {
       "rawSql": "SELECT * FROM pigsty.redis_instance"
      }
     ]
    }
   ]
  },
  {
   "title": "GPSQL Cluster",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "GPSQL Clusters",
     "type": "table",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 130 },
     "targets": [
      {
       "rawSql": "SELECT * FROM pigsty.gp_cluster"
      }
     ]
    },
    {
     "title": "GPSQL Node",
     "type": "table",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 135 },
     "targets": [
      { "rawSql": "SELECT * FROM pigsty.gp_node;" }
     ]
    },
    {
     "title": "GPSQL Node",
     "type": "table",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 140 },
     "targets": [
      {
       "rawSql": "SELECT * FROM pigsty.gp_instance;"
      }
     ]
    }
   ]
  }
 ]
}