{
 "title": "ETCD Overview",
 "description": "ETCD Service Overview",
 "tags": [
  "Pigsty",
  "ETCD",
  "Overview",
  "HOME"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cls",
    "label": "Cluster",
    "query": {
     "query": "label_values(etcd_cluster_version, cls)"
    }
   },
   {
    "name": "members",
    "label": "Members",
    "query": {
     "query": "label_values(etcd_cluster_version{cls=\"$cls\"},ip)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "ETCD Spec",
   "type": "stat",
   "description": "Members: Total number of instance in this cluster\n\nQuorum : minimal alive instances required, calculated as floor(total members / 2) + 1\n\nTolerance: max failure nodes allowed, calculated as member - quorum",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(etcd_up{job=\"etcd\", cls=\"$cls\"})",
     "legendFormat": "Instance"
    },
    {
     "expr": "count(etcd_server_id{job=\"etcd\", cls=\"$cls\"})",
     "legendFormat": "Members"
    },
    {
     "expr": "ceil(count(etcd_server_id{job=\"etcd\", cls=\"$cls\"})/ 2 + 0.1)",
     "legendFormat": "Quorum"
    },
    {
     "expr": "count(etcd_server_id{job=\"etcd\", cls=\"$cls\"}) - ceil(count(etcd_server_id{job=\"etcd\", cls=\"$cls\"})/ 2 + 0.1)",
     "legendFormat": "Tolerance"
    }
   ]
  },
  {
   "title": "ETCD Members",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "max by (ins,instance) (up{job=\"etcd\", cls=\"$cls\"})",
     "legendFormat": "{{ ins }} @ {{ instance }}"
    }
   ]
  },
  {
   "title": "ETCD Member List",
   "type": "table",
   "description": "All instances among etcd cluster ${cls}\n\nInstance: Goto PGSQL Instance\n\nIP: Goto PGSQL Node\n\nStatus: Goto PGSQL Service\n\nLoad: max(cpu,postgres,pgbouncer)\n\nSpace: Disk space usage max(all device)\n\nProxy: session number, Goto Haproxy Admin Page",
   "gridPos": { "h": 7, "w": 17, "x": 7, "y": 1 },
   "targets": [
    {
     "expr": "up{job=\"etcd\", cls=\"$cls\"}"
    },
    {
     "expr": "group by (ins,server_version) (etcd_server_version{job=\"etcd\", cls=\"$cls\"})"
    },
    {
     "expr": "max by (ins) (etcd_server_is_leader{job=\"etcd\", cls=\"$cls\"} * 2 \n+ etcd_server_is_learner{job=\"etcd\", cls=\"$cls\"})"
    },
    {
     "expr": "etcd_server_id{job=\"etcd\", cls=\"$cls\"}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(etcd_server_id{job=\"etcd\", cls=\"$cls\"}) by (cls) /\n count(etcd_server_id{job=\"etcd\", cls=\"$cls\"}) by (cls)\nor on() vector(0)",
     "legendFormat": "ETCD Health"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 3, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "min(etcd_server_has_leader{job=\"etcd\", cls=\"$cls\"}) or on() vector(0)",
     "legendFormat": "Has Leader"
    }
   ]
  },
  {
   "title": "ETCD Aliveness",
   "type": "state-timeline",
   "gridPos": { "h": 6, "w": 17, "x": 7, "y": 8 },
   "targets": [
    {
     "expr": "min(etcd_server_has_leader{job=\"etcd\", cls=\"$cls\"}) or on() vector(0)",
     "legendFormat": "ETCD Cluster Healthy"
    },
    {
     "expr": "up{job=\"etcd\", cls=\"$cls\"}",
     "legendFormat": "{{ ins }} @ {{ ip }}"
    }
   ]
  },
  {
   "type": "stat",
   "description": "Very Important Metric: This limit defines the maximum amount of data (in bytes) that can be stored in the ETCD database. When the quota is reached, further write operations will be rejected until space is freed or the quota is increased.",
   "gridPos": { "h": 4, "w": 4, "x": 3, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "etcd:cls:quota_usage{cls=\"$cls\"}",
     "legendFormat": "Quota Usage"
    }
   ]
  },
  {
   "title": "Leader Elections",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 7, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "etcd_server_leader_changes_seen_total{job=\"etcd\", cls=\"$cls\"}",
     "legendFormat": "{{ ins }} @ {{ instance }}"
    }
   ]
  },
  {
   "type": "stat",
   "description": "The current revision\n\nhttps://etcd.io/docs/v3.5/learning/data_model/",
   "gridPos": { "h": 4, "w": 3, "x": 7, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(etcd_debugging_mvcc_current_revision{cls=\"$cls\"})",
     "legendFormat": "Revision Current"
    },
    {
     "expr": "max(etcd_debugging_mvcc_compact_revision{cls=\"$cls\"})",
     "legendFormat": "Revision Compact"
    },
    {
     "expr": "max(etcd_debugging_mvcc_current_revision{cls=\"$cls\"} - etcd_debugging_mvcc_compact_revision{cls=\"$cls\"})",
     "legendFormat": "Revision Diff"
    }
   ]
  },
  {
   "type": "stat",
   "description": "Reads per minute",
   "gridPos": { "h": 4, "w": 2, "x": 10, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(etcd:ins:rpm{cls=\"$cls\"})",
     "legendFormat": "Reads/m"
    }
   ]
  },
  {
   "type": "stat",
   "description": "Reads per minute",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(etcd:ins:wpm{cls=\"$cls\"})",
     "legendFormat": "Writes/m"
    }
   ]
  },
  {
   "type": "stat",
   "description": "This metric helps monitor the latency of fsync operations, specifically focusing on the worst-case scenario (99th percentile) over the recent 5 minutes, allowing for better performance analysis and optimization of ETCD's disk I/O operations.",
   "gridPos": { "h": 4, "w": 2, "x": 14, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(etcd:ins:network_peer_rt_p95_5m{job=\"etcd\", cls=\"$cls\"})",
     "legendFormat": "Network RT"
    }
   ]
  },
  {
   "type": "stat",
   "description": "This metric helps monitor the latency of fsync operations, specifically focusing on the worst-case scenario (99th percentile) over the recent 5 minutes, allowing for better performance analysis and optimization of ETCD's disk I/O operations.",
   "gridPos": { "h": 4, "w": 2, "x": 16, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(etcd:ins:wal_fsync_rt_p95_5m{job=\"etcd\", cls=\"$cls\"})",
     "legendFormat": "Fsync RT"
    }
   ]
  },
  {
   "type": "stat",
   "description": "Database Size",
   "gridPos": { "h": 4, "w": 2, "x": 18, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (cls) (etcd_debugging_mvcc_keys_total{cls=\"$cls\"})",
     "legendFormat": "Keys"
    }
   ]
  },
  {
   "type": "stat",
   "description": "Database Size",
   "gridPos": { "h": 4, "w": 2, "x": 20, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (cls) (etcd_mvcc_db_total_size_in_bytes{cls=\"$cls\"})",
     "legendFormat": "DB Size"
    }
   ]
  },
  {
   "type": "stat",
   "description": "Totle Number of wathcher in etcd cluster",
   "gridPos": { "h": 4, "w": 2, "x": 22, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(etcd_server_quota_backend_bytes{cls=\"$cls\"})",
     "legendFormat": "Quota"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(ALERTS{alertstate=\"firing\", cls=\"$cls\", job=\"etcd\"}) or on() vector(0)",
     "legendFormat": "Firing Alert"
    },
    {
     "expr": "count(ALERTS{alertstate=\"pending\", cls=\"$cls\", job=\"etcd\"})",
     "legendFormat": "Pending Alert"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 3, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(ALERTS{job=\"etcd\", cls=\"etcd\"}) by (alertname, severity)",
     "legendFormat": "{{ alertname }}"
    }
   ]
  },
  {
   "type": "timeseries",
   "description": "Alerting event graph. Each stripe represent an alerting Event. Gray transparent stipe are pending alerts.",
   "gridPos": { "h": 4, "w": 17, "x": 7, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "ALERTS{cls=\"$cls\", alertstate=\"firing\"}",
     "legendFormat": "[{{ severity }}🔥] {{alertname}}  @ {{ ins }}"
    },
    {
     "expr": "ALERTS{cls=\"$cls\", alertstate=\"pending\"} ",
     "legendFormat": "[{{ severity }}⏰] {{alertname}}  @ {{ ins }}"
    },
    { "expr": "0", "legendFormat": "Alert" }
   ]
  },
  { "title": "Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Quota Usage",
   "type": "timeseries",
   "description": "This limit defines the maximum amount of data (in bytes) that can be stored in the ETCD database. When the quota is reached, further write operations will be rejected until space is freed or the quota is increased.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "etcd_mvcc_db_total_size_in_bytes{job=\"etcd\", cls=\"$cls\"} / etcd_server_quota_backend_bytes{job=\"etcd\", cls=\"$cls\"}",
     "legendFormat": "{{ ins }}"
    }
   ]
  },
  {
   "title": "Revision & Compact",
   "type": "timeseries",
   "description": "In ETCD, revision refers to the current version of the data stored in the cluster, incrementing with each write operation. It allows users to track changes and retrieve specific versions of keys.\n\nCompacted revision is the lowest revision number that has been retained after the compaction process, which removes old, obsolete data versions to free up space. It represents the point after which all data is considered stable and accessible, ensuring efficient storage management.",
   "gridPos": { "h": 6, "w": 8, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max by (cls) (etcd_debugging_mvcc_current_revision{job=\"etcd\", cls=\"$cls\"})",
     "legendFormat": "Current"
    },
    {
     "expr": "max by (cls) (etcd_debugging_mvcc_compact_revision{job=\"etcd\", cls=\"$cls\"})",
     "legendFormat": "Compact"
    }
   ]
  },
  {
   "type": "stat",
   "description": "When were last mvcc ddb compaction happen: https://etcd.io/docs/v3.4/op-guide/maintenance/",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "min by (cls) (etcd_debugging_mvcc_db_compaction_last{cls=\"$cls\"}) * 1000",
     "legendFormat": "Last Compact"
    },
    {
     "expr": "time() - min by (cls) (etcd_debugging_mvcc_db_compaction_last{cls=\"$cls\"})",
     "legendFormat": "Elapse"
    }
   ]
  },
  {
   "title": "Database Size",
   "type": "timeseries",
   "description": "Quota: backend limit\n\nTotal: Actual Database Size\n\nin Use: Estimated Compacted Size",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max by (cls) (etcd_mvcc_db_total_size_in_use_in_bytes{job=\"etcd\", cls=\"$cls\"} )",
     "legendFormat": "InUse"
    },
    {
     "expr": "max by (cls) (etcd_mvcc_db_total_size_in_bytes{job=\"etcd\", cls=\"$cls\"})",
     "legendFormat": "Total"
    },
    {
     "expr": "min by (cls) (etcd_server_quota_backend_bytes{job=\"etcd\", cls=\"$cls\"})",
     "legendFormat": "Quota"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"etcd\", cls=\"$cls\"}",
     "legendFormat": "{{instance}} Resident Memory"
    }
   ]
  },
  {
   "title": "Read / Write per Mintue",
   "type": "timeseries",
   "description": "▲ for read, ▼ for write ",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(etcd:ins:rpm{cls=\"$cls\"})",
     "legendFormat": "▲ Reads"
    },
    {
     "expr": "- sum(etcd:ins:wpm{cls=\"$cls\"})",
     "legendFormat": "▼ Writes"
    }
   ]
  },
  {
   "title": "Network RT (p95 5m)",
   "type": "timeseries",
   "description": "etcd network peer rt (p95 in last 5m)",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": " histogram_quantile(0.95, rate(etcd_network_peer_round_trip_time_seconds_bucket{cls=\"$cls\", job=\"etcd\"}[5m]))",
     "legendFormat": "{{ ins }} -> {{ To }}"
    }
   ]
  },
  {
   "title": "WAL Fsync RT (p95 5m)",
   "type": "timeseries",
   "description": "etcd disk wal fsync duration (p95 in last 5m)",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(etcd_disk_wal_fsync_duration_seconds_bucket{job=\"etcd\", cls=\"$cls\"}[5m])) by (ins, le))",
     "legendFormat": "{{ ins }}"
    }
   ]
  },
  {
   "title": "Peer Traffic",
   "type": "timeseries",
   "description": "▲ for Sent, ▼ for receive",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(etcd_network_peer_sent_bytes_total{job=\"etcd\", cls=\"$cls\"}[1m])) by (ins)",
     "legendFormat": "▲{{ ins }}"
    },
    {
     "expr": "- sum(rate(etcd_network_client_grpc_received_bytes_total{job=\"etcd\", cls=\"$cls\"}[1m])) by (ins)",
     "legendFormat": "▼{{ ins }}"
    }
   ]
  },
  {
   "title": "Backend Commit RT (p95 5m)",
   "type": "timeseries",
   "description": "etcd backend commit rt (p95 in last 5m)",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, rate(etcd_disk_backend_commit_duration_seconds_bucket{job=\"etcd\"}[5m]))",
     "legendFormat": "{{ ins }}"
    }
   ]
  },
  {
   "title": "Client Traffic",
   "type": "timeseries",
   "description": "▲ for Sent, ▼ for receive",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(etcd_network_client_grpc_sent_bytes_total{job=\"etcd\", cls=\"$cls\"}[1m])) by (ins)",
     "legendFormat": "▲{{ ins }}"
    },
    {
     "expr": "- sum(rate(etcd_network_peer_received_bytes_total{job=\"etcd\", cls=\"$cls\"}[1m])) by (ins)",
     "legendFormat": "▼{{ ins }}"
    }
   ]
  },
  {
   "title": "Proposal Committed",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(etcd_server_proposals_committed_total{job=\"etcd\", cls=\"$cls\"}[1m])",
     "legendFormat": "{{ ins }}"
    }
   ]
  },
  {
   "title": "Proposal Applied",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(etcd_server_proposals_applied_total{job=\"etcd\", cls=\"$cls\"}[1m])",
     "legendFormat": "{{ ins }}"
    }
   ]
  },
  { "title": "MVCC", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 59 } },
  {
   "title": "RANGE Rate1m",
   "type": "timeseries",
   "description": "Total number of RANGE seen by this etcd instance",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(etcd_mvcc_range_total{job=\"etcd\", cls=\"$cls\"}[1m])",
     "legendFormat": "{{ ins }}"
    }
   ]
  },
  {
   "title": "DELETE Rate1m",
   "type": "timeseries",
   "description": "Total number of PUT seen by this etcd instance",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(etcd_mvcc_delete_total{job=\"etcd\", cls=\"$cls\"}[1m])",
     "legendFormat": "{{ ins }}"
    }
   ]
  },
  {
   "title": "PUT Rate1m",
   "type": "timeseries",
   "description": "Total number of PUT seen by this etcd instance",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(etcd_mvcc_put_total{job=\"etcd\", cls=\"$cls\"}[1m])",
     "legendFormat": "{{ ins }}"
    }
   ]
  },
  {
   "title": "MVCC Event Rate 1m",
   "type": "timeseries",
   "description": "ETCD MVCC Event: PUT | DELETE | WATCH",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(etcd_debugging_mvcc_events_total{job=\"etcd\", cls=\"$cls\"}[1m])",
     "legendFormat": "{{ ins }}"
    }
   ]
  },
  { "title": "Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 74 } },
  {
   "title": "ETCD Logs per $__interval",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "(ip:~\"$members\" AND src:\"syslog\" AND _msg:\"etcd\") | stats by (_time:2s) count()"
    }
   ]
  },
  {
   "title": "ETCD Logs",
   "type": "logs",
   "gridPos": { "h": 18, "w": 24, "x": 0, "y": 82 },
   "targets": [
    {
     "expr": "(ip:~\"$members\" AND src:\"syslog\") |~ \"etcd\""
    }
   ]
  }
 ]
}