{
 "title": "Infra Overview",
 "description": "Pigsty Infrastructure Overview",
 "tags": [
  "Pigsty",
  "INFRA",
  "Overview",
  "HOME"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Infrastructure",
   "type": "stat",
   "gridPos": { "h": 4, "w": 14, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "1", "legendFormat": "pigsty" },
    { "expr": "1", "legendFormat": "cmdb" },
    { "expr": "1", "legendFormat": "grafana" },
    { "expr": "1", "legendFormat": "loki" },
    { "expr": "1", "legendFormat": "prometheus" },
    { "expr": "1", "legendFormat": "alertmanager" },
    { "expr": "1", "legendFormat": "etcd" },
    { "expr": "1", "legendFormat": "nginx" }
   ]
  },
  {
   "title": "Aliveness",
   "type": "stat",
   "gridPos": { "h": 10, "w": 5, "x": 14, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (ins) (up{job=\"infra\", cls!=\"nginx\"})",
     "legendFormat": "{{ ins }}"
    },
    {
     "expr": "max by (ins) (nginx_up{job=\"infra\"})",
     "legendFormat": "{{ ins }}"
    }
   ]
  },
  { "title": "Dashboards", "type": "dashlist", "gridPos": { "h": 10, "w": 5, "x": 19, "y": 1 } },
  {
   "title": "Infra Aliveness",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 14, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "up{job=\"infra\"}",
     "legendFormat": "{{ ins }} @ {{ instance }}"
    }
   ]
  },
  {
   "title": "ALERT",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "type": "stat",
     "gridPos": { "h": 7, "w": 3, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "count(ALERTS{alertstate=\"firing\", job=~\"infra|etcd\"}) or on() vector(0)",
       "legendFormat": "Firing Alert"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 7, "w": 5, "x": 3, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "count(ALERTS{alertstate=\"firing\", job=~\"infra|etcd\"}) by (alertname, severity)",
       "legendFormat": "{{ alertname }}"
      }
     ]
    },
    {
     "title": "Firing Alerts",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 11, "x": 8, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum without (ins,instance,datname) (ALERTS{alertstate=\"firing\", job=~\"infra|etcd\"})",
       "legendFormat": "[{{ severity }}] {{alertname}}  @ {{ cls }}"
      }
     ]
    },
    { "title": "Grafana Alerts", "type": "alertlist", "gridPos": { "h": 16, "w": 5, "x": 19, "y": 12 } },
    {
     "title": "Active Alerts",
     "type": "table",
     "gridPos": { "h": 9, "w": 19, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "ALERTS{job=~\"infra|etcd\"}"
      }
     ]
    }
   ]
  },
  { "title": "NGINX", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nginx_up{cls=\"nginx\"}",
     "legendFormat": "{{ ins }} @ {{ ip }}"
    }
   ]
  },
  {
   "title": "Nginx Conn Accept/Handle",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 8, "x": 5, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(nginx_connections_accepted{}[5m])",
     "legendFormat": "{{ ip }} Accecpt"
    },
    {
     "expr": "irate(nginx_connections_handled{}[5m])",
     "legendFormat": "{{ ip }} Handled"
    }
   ]
  },
  {
   "title": "Active Connections",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 11, "x": 13, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "nginx_connections_active{}", "legendFormat": "{{ ip }} active" },
    { "expr": "nginx_connections_reading{}", "legendFormat": "{{ ip }} reading" },
    { "expr": "nginx_connections_waiting{}", "legendFormat": "{{ ip }} waiting" },
    { "expr": "nginx_connections_writing{}", "legendFormat": "{{ ip }} writing" }
   ]
  },
  { "title": "VictoriaMetrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "vm_app_version{cls=\"victoriametrics\"}",
     "legendFormat": "{{ ins }} @ {{ instance }}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 5, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - process_start_time_seconds{cls=\"victoriametrics\"}",
     "legendFormat": "{{ ins }} Uptime"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vm_search_max_unique_timeseries",
     "legendFormat": "Series"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (ins) (irate(vm_rows_added_to_storage_total{}[1m]))",
     "legendFormat": "Sample / s"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(ins) (vm_promscrape_targets)",
     "legendFormat": "Targets"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(process_resident_memory_bytes{cls=\"victoriametrics\"}) by (ins)",
     "legendFormat": "Memory"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(vm_data_size_bytes{cls=\"victoriametrics\"}) by (ins)",
     "legendFormat": "Storage"
    }
   ]
  },
  { "title": "Grafana", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "grafana_build_info{cls=\"grafana\"}",
     "legendFormat": "{{ ins }} @ {{ instance }}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 5, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - process_start_time_seconds{cls=\"grafana\"}",
     "legendFormat": "{{ ins }} Uptime"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(grafana_http_request_duration_seconds_count{cls=\"grafana\"}[1m])) by (ins)",
     "legendFormat": "QPS"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, grafana_frontend_boot_first_contentful_paint_time_seconds_bucket{cls=\"grafana\"})",
     "legendFormat": "First Paint"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, grafana_frontend_boot_load_time_seconds_bucket{cls=\"grafana\"})",
     "legendFormat": "Render Full"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(process_resident_memory_bytes{cls=\"grafana\"}) by (ins)",
     "legendFormat": "Memory"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{cls=\"grafana\"}[1m])",
     "legendFormat": "CPU"
    }
   ]
  },
  { "title": "VictoriaLogs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "vm_app_version{cls=\"victorialogs\"}",
     "legendFormat": "{{ ins }} @ {{ instance }}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 5, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - process_start_time_seconds{cls=\"victorialogs\"}",
     "legendFormat": "{{ ins }} Uptime"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(vl_bytes_ingested_total{cls=\"victorialogs\"}[5m])) by (ins)",
     "legendFormat": "Bytes / s"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(vl_rows_ingested_total{cls=\"victorialogs\"}[5m])) by (ins)",
     "legendFormat": "Lines / s"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vl_uncompressed_data_size_bytes{type=\"storage/small\"} / vl_compressed_data_size_bytes{type=\"storage/small\"}",
     "legendFormat": "Compression"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(process_resident_memory_bytes{cls=\"victorialogs\"}) by (ins)",
     "legendFormat": "Memory"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(vl_data_size_bytes{cls=\"victorialogs\"}) by (ins)",
     "legendFormat": "Storage"
    }
   ]
  },
  { "title": "ETCD", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "ETCD Members",
   "type": "stat",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 33 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "max by (ins,instance) (up{job=\"etcd\", cls=\"etcd\"})",
     "legendFormat": "{{ ins }} @ {{ instance }}"
    }
   ]
  },
  {
   "title": "ETCD Aliveness",
   "type": "state-timeline",
   "gridPos": { "h": 6, "w": 17, "x": 7, "y": 33 },
   "targets": [
    {
     "expr": "up{job=\"etcd\", cls=\"etcd\"}",
     "legendFormat": "{{ ins }} @ {{ ip }}"
    },
    {
     "expr": "min(etcd_server_has_leader{job=\"etcd\", cls=\"etcd\"}) or on() vector(0)",
     "legendFormat": "ETCD Has Leader?"
    }
   ]
  }
 ]
}