{
 "title": "Logs Instance",
 "description": "Logs for Single Node/Instance",
 "tags": [
  "Pigsty",
  "INFRA",
  "Instance",
  "NODE"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "ins", "label": "Instance", "query": { "query": "" } },
   {
    "name": "src",
    "label": "Source",
    "query": {
     "query": "{ins=\"$ins\"}"
    }
   },
   { "name": "search", "label": "Search" }
  ]
 },
 "panels": [
  {
   "title": "Logs per $__interval",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "ins:\"$ins\" AND src:\"$src\" | stats by (_time:$__interval) count()"
    }
   ]
  },
  {
   "title": "Searched Logs per $__interval",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "ins:\"$ins\" AND src:\"$src\" |~ \"$search\" | stats by (_time:$__interval) count()"
    }
   ]
  },
  {
   "title": "Recent Logs",
   "type": "logs",
   "gridPos": { "h": 18, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "ins:\"$ins\" AND src:\"$src\" |~ \"$search\""
    }
   ]
  }
 ]
}