{
 "title": "Loki Overview",
 "description": "Pigsty Loki Overview: https://grafana.com/docs/loki/latest/operations/observability/",
 "tags": [
  "Pigsty",
  "INFRA",
  "LOKI"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "ins",
    "label": "Loki",
    "query": {
     "query": "label_values(loki_build_info, ins)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (version) (loki_build_info{ins=\"$ins\"})",
     "legendFormat": "Loki"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - process_start_time_seconds{ins=\"$ins\"}",
     "legendFormat": "Uptime"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(loki_distributor_bytes_received_total{ins=\"$ins\"}[5m])) by (tenant)",
     "legendFormat": "Bytes / s"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(loki_distributor_lines_received_total{ins=\"$ins\"}[5m]))",
     "legendFormat": "Lines / s"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(loki_ingester_chunk_compression_ratio_bucket{ins=\"$ins\"}[5m])) by (le))",
     "legendFormat": "Compress Ratio"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{ins=\"$ins\"}[1m])",
     "legendFormat": "CPU"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{ins=\"$ins\"}",
     "legendFormat": "Memory"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(loki_ingester_chunk_stored_bytes_total{ins=\"$ins\"})",
     "legendFormat": "Storage"
    }
   ]
  },
  { "title": "Loki API", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Loki API Response Time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(loki_request_duration_seconds_bucket{ins=\"$ins\"}[5m])) by (le,route))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Distributor", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Received  Lines/s",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (tenant) (rate(loki_distributor_lines_received_total{ins=\"$ins\"}[5m]))",
     "legendFormat": "distributor / {{ tenant}}"
    }
   ]
  },
  {
   "title": "Received bytes/s",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(loki_distributor_bytes_received_total{ins=\"$ins\"}[5m])) by (tenant)",
     "legendFormat": "distributor / {{tenant}}"
    }
   ]
  },
  {
   "title": "Distributor Batchs/s",
   "type": "timeseries",
   "description": "Batch appends sent to ingesters / sec",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(loki_distributor_ingester_appends_total{ins=\"$ins\"}[5m])",
     "legendFormat": "successed"
    },
    {
     "expr": "rate(loki_distributor_ingester_append_failures_total{ins=\"$ins\"}[5m])",
     "legendFormat": "failed"
    }
   ]
  },
  { "title": "Ingester", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Blocks / Chunk",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(loki_ingester_blocks_per_chunk_bucket{ins=\"$ins\"}[5m])) by (le))",
     "legendFormat": "blocks"
    }
   ]
  },
  {
   "title": "Chunk Size",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(loki_ingester_chunk_size_bytes_bucket{ins=\"$ins\"}[5m])) by (le))",
     "legendFormat": "chunk size"
    }
   ]
  },
  {
   "title": "Chunk Age",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(loki_ingester_chunk_age_seconds_bucket{ins=\"$ins\"}[5m])) by (le))",
     "legendFormat": "ages"
    }
   ]
  },
  {
   "title": "Chunk Compression Ratios",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(loki_ingester_chunk_compression_ratio_bucket{ins=\"$ins\"}[5m])) by (le))",
     "legendFormat": "ratio"
    }
   ]
  },
  {
   "title": "Chunk Encode Time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(loki_ingester_chunk_encode_time_seconds_bucket{ins=\"$ins\"}[5m])) by (le))",
     "legendFormat": "durations."
    }
   ]
  },
  {
   "title": "Lines / Chunk",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(loki_ingester_chunk_entries_bucket{ins=\"$ins\"}[5m])) by (le))",
     "legendFormat": "lines"
    }
   ]
  },
  {
   "title": "Chunks in Memory",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "loki_ingester_memory_chunks{ins=\"$ins\"}",
     "legendFormat": "chunks"
    }
   ]
  },
  {
   "title": "Chunk Status",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 16, "x": 8, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(loki_ingester_chunks_created_total{ins=\"$ins\"}[5m])",
     "legendFormat": "create"
    },
    {
     "expr": "sum by (reason) (rate(loki_ingester_chunks_flushed_total{ins=\"$ins\"}[5m]))",
     "legendFormat": "flush / {{ reason }}"
    },
    {
     "expr": "sum by (fake) (rate(loki_ingester_chunks_stored_total{ins=\"$ins\"}[5m]))",
     "legendFormat": "stored"
    }
   ]
  },
  {
   "title": "Chunks in Streams",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (tenan) (loki_ingester_memory_streams{ins=\"$ins\"})",
     "legendFormat": "streams"
    }
   ]
  },
  {
   "title": "Streams Stats",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 16, "x": 8, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(loki_ingester_streams_created_total{ins=\"$ins\"}[5m])",
     "legendFormat": "create"
    },
    {
     "expr": "rate(loki_ingester_streams_removed_total{ins=\"$ins\"}[5m])",
     "legendFormat": "delete"
    }
   ]
  }
 ]
}