{
 "title": "Vector",
 "tags": [ "Vector" ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": {
     "query": "label_values(vector_adaptive_concurrency_averaged_rtt_bucket,instance)"
    }
   },
   {
    "name": "input_plugin",
    "label": "source",
    "query": {
     "query": "query_result(vector_component_received_events_total{instance=~'$instance',component_kind=\"source\",component_id!~'vector_metrics'})"
    }
   },
   {
    "name": "output_plugin",
    "label": "sink",
    "query": {
     "query": "query_result(vector_component_sent_events_total{instance=~'$instance',component_kind=\"sink\",component_id!~'prometheus'})"
    }
   },
   {
    "name": "plugin_id",
    "label": "transform",
    "query": {
     "query": "vector_component_sent_events_total{instance=~'$instance',component_kind!=\"sink\",component_kind=\"transform\",component_id!~'prometheus_s'}"
    }
   }
  ]
 },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": " ",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "up{instance='$instance'}", "legendFormat": "UP" }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(vector_component_received_events_total{instance=~'$instance',component_kind=\"source\",component_id=~'$input_plugin'}[$__range]))",
     "legendFormat": "IN"
    },
    {
     "expr": "sum(increase(vector_component_sent_events_total{instance='$instance',component_kind=\"sink\",component_id=~'$output_plugin'}[$__range]))",
     "legendFormat": "OUT"
    },
    {
     "expr": "round(sum(increase(vector_component_received_events_total{instance='$instance',component_kind=\"source\",component_id=~'$input_plugin'}[$__range]))-sum(increase(vector_component_sent_events_total{instance='$instance',component_kind=\"sink\",component_id=~'$output_plugin'}[$__range])))",
     "legendFormat": "Diff"
    }
   ]
  },
  {
   "title": "Source Errors",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(vector_component_errors_total{instance='$instance',component_kind=\"source\",component_id=~'$input_plugin'}[$__range])) or 0",
     "legendFormat": "IN"
    }
   ]
  },
  {
   "title": "Transform Errors",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 11, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(vector_component_errors_total{instance='$instance',component_kind=\"transform\",component_id=~'$plugin_id'}[$__range])) or 0",
     "legendFormat": "OUT"
    }
   ]
  },
  {
   "title": "Sink Errors",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 14, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(vector_component_errors_total{instance='$instance',component_kind=\"sink\",component_id=~'$output_plugin'}[$__range])) or 0",
     "legendFormat": "OUT"
    }
   ]
  },
  {
   "title": "Reload count",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 17, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vector_reloaded_total{instance=~'$instance'} or 0",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Lua Memory Used",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vector_lua_memory_used_bytes{instance=~'$instance'} or 0",
     "legendFormat": "{{component_id}}"
    }
   ]
  },
  {
   "title": " ",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vector_uptime_seconds{instance=~'$instance'}",
     "legendFormat": "UP"
    }
   ]
  },
  {
   "title": "Source Discard",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 8, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(vector_component_discarded_events_total{instance='$instance',component_kind=\"source\",component_id=~'$input_plugin'}[$__range])) or 0",
     "legendFormat": "IN"
    }
   ]
  },
  {
   "title": "Transform Discard",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 11, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(vector_component_discarded_events_total{instance=~'$instance',component_kind=\"transform\",component_id=~'$plugin_id'}[$__range])) or 0",
     "legendFormat": "Transform"
    }
   ]
  },
  {
   "title": "Sink Discard",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 14, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(vector_component_discarded_events_total{instance=~'$instance',component_kind=\"sink\",component_id=~'$output_plugin'}[$__range])) or 0",
     "legendFormat": "OUT"
    }
   ]
  },
  {
   "title": "Sink Discard/Sent",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 20, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(irate(vector_component_discarded_events_total{instance='$instance',component_kind=\"sink\",component_id=~'$output_plugin'}[$__rate_interval]))",
     "legendFormat": "Sink Discard"
    },
    {
     "expr": "sum(irate(vector_component_sent_events_total{instance='$instance',component_kind=\"sink\",component_id=~'$output_plugin'}[$__rate_interval]))",
     "legendFormat": "Sent Success"
    }
   ]
  },
  {
   "title": "Sink Stats",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(vector_component_sent_events_total{instance='$instance',component_kind=\"sink\",component_id=~'$output_plugin'}[$__range]))",
     "legendFormat": "Sink Success"
    },
    {
     "expr": "sum(increase(vector_component_discarded_events_total{instance='$instance',component_kind=\"sink\",component_id=~'$output_plugin'}[$__range]))",
     "legendFormat": "Sink Errors"
    }
   ]
  },
  {
   "title": "Files",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "Open FIles",
     "type": "piechart",
     "description": "The total number of open files. (For \"File\" source)",
     "gridPos": { "h": 7, "w": 5, "x": 0, "y": 16 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "vector_open_files{instance=~'$instance'}",
       "legendFormat": "{{component_id}}"
      }
     ]
    },
    {
     "title": "Add FIles",
     "type": "timeseries",
     "description": "The number of files Vector has found to watch.",
     "gridPos": { "h": 7, "w": 6, "x": 5, "y": 16 },
     "targets": [
      {
       "expr": "rate(vector_files_added_total{instance=~'$instance',component_id=~'$input_plugin'}[$__range])",
       "legendFormat": "{{component_id}}"
      }
     ]
    },
    {
     "title": "CheckSum Errors",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 3, "x": 11, "y": 16 },
     "targets": [
      {
       "expr": "rate(vector_checksum_errors_total{instance='$instance'}[$__range])",
       "legendFormat": "{{component_id}}"
      }
     ]
    }
   ]
  },
  { "title": "Source", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Source Received Bytes",
   "type": "timeseries",
   "description": "The number of raw bytes accepted by this component from source origins.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "irate(vector_component_received_bytes_total{instance='$instance',component_kind=\"source\",component_id=~'$input_plugin'}[$__rate_interval])",
     "legendFormat": "{{component_id}}"
    }
   ]
  },
  {
   "title": "Source Errors",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 17 },
   "targets": [
    {
     "expr": "irate(vector_component_errors_total{instance='$instance',component_kind=\"source\",component_id=~'$input_plugin'}[$__rate_interval])",
     "legendFormat": "{{component_id}}"
    }
   ]
  },
  {
   "title": "Discarded Events",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 17 },
   "targets": [
    {
     "expr": "irate(vector_component_discarded_events_total{instance=~'$instance',component_kind=\"source\",component_id=~'$input_plugin'}[$__rate_interval])",
     "legendFormat": "{{component_id}}"
    }
   ]
  },
  {
   "title": "Source Received Events Bytes",
   "type": "timeseries",
   "description": "The number of event bytes accepted by this component either from tagged origins like file and uri, or cumulatively from other origins.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "irate(vector_component_received_event_bytes_total{instance='$instance',component_kind=\"source\",component_id=~'$input_plugin'}[$__rate_interval])",
     "legendFormat": "{{component_id}}"
    }
   ]
  },
  {
   "title": "Source Received Events",
   "type": "timeseries",
   "description": "The number of events accepted by this component either from tagged origins like file and uri, or cumulatively from other origins.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "irate(vector_component_received_events_total{instance='$instance',component_kind=\"source\",component_id=~'$input_plugin'}[$__rate_interval])",
     "legendFormat": "{{component_id}}"
    }
   ]
  },
  {
   "title": "Source Sent Events Bytes",
   "type": "timeseries",
   "description": "The number of event bytes accepted by this component either from tagged origins like file and uri, or cumulatively from other origins.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "irate(vector_component_sent_event_bytes_total{instance='$instance',component_kind=\"source\",component_id=~'$input_plugin'}[$__rate_interval])",
     "legendFormat": "{{component_id}}"
    }
   ]
  },
  {
   "title": "Source Sent Events",
   "type": "timeseries",
   "description": "The number of events accepted by this component either from tagged origins like file and uri, or cumulatively from other origins.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "irate(vector_component_sent_events_total{instance='$instance',component_kind=\"source\",component_id=~'$input_plugin'}[$__rate_interval])",
     "legendFormat": "{{component_id}}"
    }
   ]
  },
  {
   "title": "Lag Event Time Ingest quantile",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 14, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(vector_source_lag_time_seconds_bucket{component_id=~'$input_plugin',instance='$instance', component_kind=\"source\"}[$__rate_interval])) by (le))",
     "legendFormat": "99 percentile"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(vector_source_lag_time_seconds_bucket{component_id=~'$input_plugin',instance='$instance', component_kind=\"source\"}[$__rate_interval])) by (le))",
     "legendFormat": "95 percentile"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(vector_source_lag_time_seconds_bucket{component_id=~'$input_plugin',instance='$instance', component_kind=\"source\"}[$__rate_interval])) by (le))",
     "legendFormat": "90 percentile"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(vector_source_lag_time_seconds_bucket{component_id=~'$input_plugin',instance='$instance', component_kind=\"source\"}[$__rate_interval])) by (le))",
     "legendFormat": "50 percentile"
    }
   ]
  },
  {
   "title": "Lag Event Time Ingest",
   "type": "heatmap",
   "description": "The difference between the timestamp recorded in each event and the time when it was ingested, expressed as fractional seconds.",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 40 },
   "targets": [
    {
     "expr": "sum(rate(vector_source_lag_time_seconds_bucket{component_id=~'$input_plugin',instance='$instance',component_kind='source'}[$__range])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Lag Event Time Ingest",
   "type": "bargauge",
   "description": "The difference between the timestamp recorded in each event and the time when it was ingested, expressed as fractional seconds.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 48 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(vector_source_lag_time_seconds_bucket{component_id=~'$input_plugin',instance='$instance',component_kind='source'}[$__range])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  { "title": "Transform", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 56 } },
  { "title": " ", "type": "text", "gridPos": { "h": 7, "w": 6, "x": 0, "y": 57 }, "options": { "content": "# Post something here!" } },
  {
   "title": "Transform Errors",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 6, "y": 57 },
   "targets": [
    {
     "expr": "irate(vector_component_errors_total{instance='$instance',component_kind=\"transform\",component_id=~'$plugin_id'}[$__rate_interval])",
     "legendFormat": "{{component_id}}"
    }
   ]
  },
  {
   "title": "Discarded Events",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 57 },
   "targets": [
    {
     "expr": "irate(vector_component_discarded_events_total{instance=~'$instance',component_kind=\"transform\",component_id=~'$plugin_id'}[$__rate_interval])",
     "legendFormat": "{{component_id}}"
    }
   ]
  },
  {
   "title": "Transform Received Events Bytes",
   "type": "timeseries",
   "description": "The number of event bytes accepted by this component either from tagged origins like file and uri, or cumulatively from other origins.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "irate(vector_component_received_event_bytes_total{instance='$instance',component_kind=\"transform\",component_id=~'$plugin_id'}[$__rate_interval])",
     "legendFormat": "{{component_id}}"
    }
   ]
  },
  {
   "title": "Transform Received Events",
   "type": "timeseries",
   "description": "The number of events accepted by this component either from tagged origins like file and uri, or cumulatively from other origins.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "irate(vector_component_received_events_total{instance='$instance',component_kind=\"transform\",component_id=~'$plugin_id'}[$__rate_interval])",
     "legendFormat": "{{component_id}}"
    }
   ]
  },
  {
   "title": "Transform Sent Events Bytes",
   "type": "timeseries",
   "description": "The number of event bytes accepted by this component either from tagged origins like file and uri, or cumulatively from other origins.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "irate(vector_component_sent_event_bytes_total{instance='$instance',component_kind=\"transform\",component_id=~'$plugin_id'}[$__rate_interval])",
     "legendFormat": "{{component_id}} - {{output}}"
    }
   ]
  },
  {
   "title": "Transform Sent Events",
   "type": "timeseries",
   "description": "The number of events accepted by this component either from tagged origins like file and uri, or cumulatively from other origins.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "irate(vector_component_sent_events_total{instance='$instance',component_kind=\"transform\",component_id=~'$plugin_id'}[$__rate_interval])",
     "legendFormat": "{{component_id}}"
    }
   ]
  },
  { "title": "Transform Buffer Buckets", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 80 } },
  {
   "title": "Buffer Send Duration Sec ",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 81 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(vector_buffer_send_duration_seconds_bucket{component_id=~'$plugin_id',instance='$instance',component_kind='transform'}[$__range])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Buffer Send Duration Sec ",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 89 },
   "targets": [
    {
     "expr": "sum(rate(vector_buffer_send_duration_seconds_bucket{component_id=~'$plugin_id',instance='$instance',component_kind='transform'}[$__range])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  { "title": "Sink Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 97 } },
  { "title": " ", "type": "text", "gridPos": { "h": 7, "w": 5, "x": 0, "y": 98 }, "options": { "content": "# Post something here!" } },
  {
   "title": "Sink Errors",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 5, "y": 98 },
   "targets": [
    {
     "expr": "irate(vector_component_errors_total{instance='$instance',component_kind=\"sink\",component_id=~'$output_plugin'}[$__rate_interval])",
     "legendFormat": "{{component_id}}"
    }
   ]
  },
  {
   "title": "Discarded Events",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 98 },
   "targets": [
    {
     "expr": "irate(vector_component_discarded_events_total{instance=~'$instance',component_kind=\"sink\",component_id=~'$output_plugin'}[$__rate_interval])",
     "legendFormat": "{{component_id}}"
    }
   ]
  },
  {
   "title": "Sink Received Events Bytes",
   "type": "timeseries",
   "description": "The number of event bytes accepted by this component either from tagged origins like file and uri, or cumulatively from other origins.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 105 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "irate(vector_component_received_event_bytes_total{instance='$instance',component_kind=\"sink\",component_id=~'$output_plugin'}[$__rate_interval])",
     "legendFormat": "{{component_id}}"
    }
   ]
  },
  {
   "title": "Sink Received Events",
   "type": "timeseries",
   "description": "The number of events accepted by this component either from tagged origins like file and uri, or cumulatively from other origins.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 105 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "irate(vector_component_received_events_total{instance='$instance',component_kind=\"sink\",component_id=~'$output_plugin'}[$__rate_interval])",
     "legendFormat": "{{component_id}}"
    }
   ]
  },
  {
   "title": "Sink Sent Events Bytes",
   "type": "timeseries",
   "description": "The number of event bytes accepted by this component either from tagged origins like file and uri, or cumulatively from other origins.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 113 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "irate(vector_component_sent_event_bytes_total{instance='$instance',component_kind=\"sink\",component_id=~'$output_plugin'}[$__rate_interval])",
     "legendFormat": "{{component_id}}"
    }
   ]
  },
  {
   "title": "Sink Sent Events",
   "type": "timeseries",
   "description": "The number of events accepted by this component either from tagged origins like file and uri, or cumulatively from other origins.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 113 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "irate(vector_component_sent_events_total{instance='$instance',component_kind=\"sink\",component_id=~'$output_plugin'}[$__rate_interval])",
     "legendFormat": "{{component_id}}"
    }
   ]
  },
  { "title": "Sink Buffers Stats", "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 121 } },
  {
   "title": "Sink Max Buffer Size (events)",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 122 },
   "targets": [
    {
     "expr": "vector_buffer_max_event_size{instance='$instance',component_id=~'$output_plugin'}",
     "legendFormat": "{{component_id}}"
    }
   ]
  },
  {
   "title": "Buffer Recived Bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 129 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "irate(vector_buffer_received_bytes_total{instance='$instance',component_id=~'$output_plugin'}[$__rate_interval])",
     "legendFormat": "{{component_id}} - {{buffer_type}}"
    }
   ]
  },
  {
   "title": "Buffer Recived Events",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 129 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "irate(vector_buffer_received_events_total{instance='$instance',component_id=~'$output_plugin'}[$__rate_interval])",
     "legendFormat": "{{component_id}} - {{buffer_type}}"
    }
   ]
  },
  {
   "title": "Buffer Sent Bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 137 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "irate(vector_buffer_sent_bytes_total{instance='$instance',component_id=~'$output_plugin'}[$__rate_interval])",
     "legendFormat": "{{component_id}} - {{buffer_type}}"
    }
   ]
  },
  {
   "title": "Buffer Sent Events",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 137 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "irate(vector_buffer_sent_events_total{instance='$instance',component_id=~'$output_plugin'}[$__rate_interval])",
     "legendFormat": "{{component_id}} - {{buffer_type}}"
    }
   ]
  },
  {
   "title": "Sink Buffer size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 145 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "targets": [
    {
     "expr": "vector_buffer_byte_size{instance='$instance',component_id=~'$output_plugin'}",
     "legendFormat": "{{component_id}} - {{buffer_type}}"
    }
   ]
  },
  {
   "title": "Sink Buffer Events",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 145 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "vector_buffer_events{instance='$instance',component_id=~'$output_plugin'}",
     "legendFormat": "{{component_id}} - {{buffer_type}}"
    }
   ]
  },
  {
   "title": "Sink Buffer Buckets",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 153 },
   "collapsed": true,
   "panels": [
    {
     "title": "Buffer Send Duration Sec ",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 540 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(vector_buffer_send_duration_seconds_bucket{component_id=~'$output_plugin',instance='$instance',component_kind='sink'}[$__range])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Buffer Send Duration Sec ",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 548 },
     "targets": [
      {
       "expr": "sum(rate(vector_buffer_send_duration_seconds_bucket{component_id=~'$output_plugin',instance='$instance',component_kind='sink'}[$__range])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    }
   ]
  },
  { "title": "Sink Kafka", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 154 } },
  {
   "title": "Kafka Queue Message Bytes",
   "type": "timeseries",
   "description": "Current total size of messages in producer queues.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 155 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "vector_kafka_queue_messages_bytes{instance='$instance',component_kind=\"sink\",component_id=~'$output_plugin'}",
     "legendFormat": "{{component_id}}"
    }
   ]
  },
  {
   "title": "Kafka Queue Messages",
   "type": "timeseries",
   "description": "Current number of messages in producer queues.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 155 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "vector_kafka_queue_messages{instance='$instance',component_kind=\"sink\",component_id=~'$output_plugin'}",
     "legendFormat": "{{component_id}}"
    }
   ]
  },
  {
   "title": "Kafka Produced Message Bytes",
   "type": "timeseries",
   "description": "Total number of message bytes (including framing, such as per-Message framing and MessageSet/batch framing) transmitted to Kafka brokers.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 163 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "irate(vector_kafka_produced_messages_bytes_total{instance='$instance',component_kind=\"sink\",component_id=~'$output_plugin'}[$__rate_interval])",
     "legendFormat": "{{component_id}}"
    }
   ]
  },
  {
   "title": "Kafka Produced Messages",
   "type": "timeseries",
   "description": "Total number of messages transmitted (produced) to Kafka brokers.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 163 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "irate(vector_kafka_produced_messages_total{instance='$instance',component_kind=\"sink\",component_id=~'$output_plugin'}[$__rate_interval])",
     "legendFormat": "{{component_id}}"
    }
   ]
  },
  {
   "title": "Kafka Requests Transmitted Bytes to Broker",
   "type": "timeseries",
   "description": "Total number of bytes transmitted to Kafka brokers.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 171 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "irate(vector_kafka_requests_bytes_total{instance='$instance',component_kind=\"sink\",component_id=~'$output_plugin'}[$__rate_interval])",
     "legendFormat": "{{component_id}}"
    }
   ]
  },
  {
   "title": "Kafka Requests Sent to Broker",
   "type": "timeseries",
   "description": "Total number of requests sent to Kafka brokers.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 171 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "irate(vector_kafka_requests_total{instance='$instance',component_kind=\"sink\",component_id=~'$output_plugin'}[$__rate_interval])",
     "legendFormat": "{{component_id}}"
    }
   ]
  },
  {
   "title": "Kafka Response Bytes from Broker",
   "type": "timeseries",
   "description": "Total number of bytes received from Kafka brokers.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 179 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "irate(vector_kafka_responses_bytes_total{instance='$instance',component_kind=\"sink\",component_id=~'$output_plugin'}[$__rate_interval])",
     "legendFormat": "{{component_id}}"
    }
   ]
  },
  {
   "title": "Kafka Response from Broker",
   "type": "timeseries",
   "description": "Total number of responses received from Kafka brokers.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 179 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "irate(vector_kafka_responses_total{instance='$instance',component_kind=\"sink\",component_id=~'$output_plugin'}[$__rate_interval])",
     "legendFormat": "{{component_id}}"
    }
   ]
  }
 ]
}