---
#--------------------------------------------------------------#
# Install Vector                                 [vector_install]
#--------------------------------------------------------------#
- name: install vector
  tags: [vector, vector_install]
  block:
    - name: install vector package
      package: name=vector state=present
    - name: create vector systemd service
      template: 
        src: vector.service 
        dest: "{{ systemd_dir }}/vector.service"

#--------------------------------------------------------------#
# Config Vector                                  [vector_config]
#--------------------------------------------------------------#
- name: config vector
  tags: [vector, vector_config]
  block:
    - name: create vector directories
      file:
        path: "{{ item }}"
        state: directory
      loop:
        - "{{ vector_config_dir }}"
        - "{{ vector_data_dir }}"
        - /var/log/vector

    - name: check if docker socket exists (auto-detection)
      stat:
        path: "{{ vector_docker_socket }}"
      register: docker_socket_stat

    - name: render /etc/vector/vector.yml config
      template: 
        src: vector.yml 
        dest: /etc/vector/vector.yml

#--------------------------------------------------------------#
# Launch Vector                                  [vector_launch]
#--------------------------------------------------------------#
- name: launch vector
  tags: [vector, vector_launch]
  when: vector_enabled|bool
  block:
    - name: restart vector systemd service
      systemd: name=vector state=restarted enabled=yes daemon_reload=yes
    
    - name: wait for vector service online
      wait_for: host=127.0.0.1 port={{ vector_port }} state=started timeout=20
